# importing the required library
library(openxlsx)

# specifying the path name
path <- "/home/tchemit/projects/iotc/2025/ROS_DATA_TO_INPUT/SEYCHELLES/ROS_PS_data_reporting_SYC_2023.xlsx"

# getting data from sheets
sheets <- as.list(openxlsx::getSheetNames(path))
sheets <- sheets[-1]
print(sheets)

# Pure Seine - Model 3.2.1
#[ 1] = "META" | Skip
#[ 2] = "O-INFO" | From row 6 - 25 columns
O_INFO_NAMES <- c("OBSERVED_TRIP_NUMBER",
                  "OBSERVER_IDENTIFICATION_OBSERVER_IOTC_NUMBER",
                  "OBSERVER_IDENTIFICATION_FULL_NAME",
                  "OBSERVER_IDENTIFICATION_NATIONALITY_CODE",
                  "OBSERVER_TRIP_DETAILS_EMBARKATION_IN_PORT_COUNTRY_CODE",
                  "OBSERVER_TRIP_DETAILS_EMBARKATION_IN_PORT_PORT_CODE",
                  "OBSERVER_TRIP_DETAILS_EMBARKATION_AT_SEA_LATITUDE",
                  "OBSERVER_TRIP_DETAILS_EMBARKATION_AT_SEA_LONGITUDE",
                  "OBSERVER_TRIP_DETAILS_EMBARKATION_AT_SEA_TIMESTAMP",
                  "OBSERVER_TRIP_DETAILS_DISEMBARKATION_IN_PORT_COUNTRY_CODE",
                  "OBSERVER_TRIP_DETAILS_DISEMBARKATION_IN_PORT_PORT_CODE",
                  "OBSERVER_TRIP_DETAILS_DISEMBARKATION_AT_SEA_LATITUDE",
                  "OBSERVER_TRIP_DETAILS_DISEMBARKATION_AT_SEA_LONGITUDE",
                  "OBSERVER_TRIP_DETAILS_DISEMBARKATION_AT_SEA_TIMESTAMP",
                  "OBSERVED_TRIP_SUMMARY_NUMBER_OF_SETS_CONDUCTED",
                  "OBSERVED_TRIP_SUMMARY_NUMBER_OF_SETS_OBSERVED",
                  "OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_SEARCHING",
                  "OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_ACTIVELY_FISHING",
                  "OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_IN_FISHING_AREA",
                  "OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_TRANSITING",
                  "OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_LOST",
                  "OBSERVED_TRIP_SUMMARY_REASONS_FOR_DAYS_LOST_REASON_1_CODE",
                  "OBSERVED_TRIP_SUMMARY_REASONS_FOR_DAYS_LOST_REASON_2_CODE",
                  "OBSERVED_TRIP_SUMMARY_REASONS_FOR_DAYS_LOST_REASON_3_CODE",
                  "OBSERVED_TRIP_SUMMARY_REASONS_FOR_DAYS_LOST_REASON_4_CODE")

#[ 3] = "V-INFO" | From row 6 - 32 columns
V_INFO_NAMES <- c("OBSERVED_TRIP_NUMBER",
                  "VESSEL_INFORMATION_IDENTIFICATION_NAME",
                  "VESSEL_INFORMATION_IDENTIFICATION_FLAG_OR_CHARTERING_CODE",
                  "VESSEL_INFORMATION_IDENTIFICATION_IOTC_NUMBER",
                  "VESSEL_INFORMATION_IDENTIFICATION_IMO_NUMBER",
                  "VESSEL_INFORMATION_IDENTIFICATION_IRCS",
                  "VESSEL_INFORMATION_IDENTIFICATION_REGISTRATION_COUNTRY_CODE",
                  "VESSEL_INFORMATION_IDENTIFICATION_REGISTRATION_PORT_CODE",
                  "VESSEL_INFORMATION_IDENTIFICATION_REGISTRATION_NUMBER",
                  "VESSEL_INFORMATION_IDENTIFICATION_CONTACT_PHONE_1",
                  "VESSEL_INFORMATION_IDENTIFICATION_CONTACT_PHONE_2",
                  "VESSEL_INFORMATION_IDENTIFICATION_CONTACT_FAX_1",
                  "VESSEL_INFORMATION_IDENTIFICATION_CONTACT_FAX_2",
                  "VESSEL_INFORMATION_IDENTIFICATION_CONTACT_EMAIL_1",
                  "VESSEL_INFORMATION_IDENTIFICATION_CONTACT_EMAIL_2",
                  "VESSEL_INFORMATION_IDENTIFICATION_LICENSED_TARGET_SPECIES_SPECIES_1_CODE",
                  "VESSEL_INFORMATION_IDENTIFICATION_LICENSED_TARGET_SPECIES_SPECIES_2_CODE",
                  "VESSEL_INFORMATION_IDENTIFICATION_LICENSED_TARGET_SPECIES_SPECIES_3_CODE",
                  "VESSEL_INFORMATION_IDENTIFICATION_LICENSED_TARGET_SPECIES_SPECIES_4_CODE",
                  "VESSEL_INFORMATION_IDENTIFICATION_MAIN_FISHING_GEAR_CODE",
                  "VESSEL_INFORMATION_OWNER_AND_PERSONNEL_OWNER_FULL_NAME",
                  "VESSEL_INFORMATION_OWNER_AND_PERSONNEL_OWNER_NATIONALITY_CODE",
                  "VESSEL_INFORMATION_OWNER_AND_PERSONNEL_OWNER_CONTACT_DETAILS",
                  "VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CHARTER_OR_OPERATOR_FULL_NAME",
                  "VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CHARTER_OR_OPERATOR_NATIONALITY_CODE",
                  "VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CHARTER_OR_OPERATOR_CONTACT_DETAILS",
                  "VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CHARTER_OR_OPERATOR_CONTACT_DETAILS2",
                  "VESSEL_INFORMATION_OWNER_AND_PERSONNEL_FISHING_MASTER_FULL_NAME",
                  "VESSEL_INFORMATION_OWNER_AND_PERSONNEL_FISHING_MASTER_NATIONALITY_CODE",
                  "VESSEL_INFORMATION_OWNER_AND_PERSONNEL_SKIPPER_CAPTAIN_FULL_NAME",
                  "VESSEL_INFORMATION_OWNER_AND_PERSONNEL_SKIPPER_CAPTAIN_NATIONALITY_CODE",
                  "VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CREW_NUMBER")

#[ 4] = "V-TRIP" | From row 6 - 11 columns
V_TRIP_NAMES = c("OBSERVED_TRIP_NUMBER",
                 "TRIP_DETAILS_VESSEL_DEPARTURE_PORT_COUNTRY_CODE",
                 "TRIP_DETAILS_VESSEL_DEPARTURE_PORT_PORT_CODE",
                 "TRIP_DETAILS_VESSEL_DEPARTURE_PORT_LATITUDE",
                 "TRIP_DETAILS_VESSEL_DEPARTURE_PORT_LONGITUDE",
                 "TRIP_DETAILS_VESSEL_DEPARTURE_TIMESTAMP",
                 "TRIP_DETAILS_VESSEL_RETURN_PORT_COUNTRY_CODE",
                 "TRIP_DETAILS_VESSEL_RETURN_PORT_PORT_CODE",
                 "TRIP_DETAILS_VESSEL_RETURN_PORT_LATITUDE",
                 "TRIP_DETAILS_VESSEL_RETURN_PORT_LONGITUDE",
                 "TRIP_DETAILS_VESSEL_RETURN_TIMESTAMP")

#[ 5] = "V-ATTRIBUTES" | From row 6 - 50 columns
V_ATTRIBUTES_NAMES <- c("OBSERVED_TRIP_NUMBER",
                        "VESSEL_ATTRIBUTES_TONNAGE_VALUE",
                        "VESSEL_ATTRIBUTES_TONNAGE_GT_GRT",
                        "VESSEL_ATTRIBUTES_LENGTH_OVERALL_VALUE",
                        "VESSEL_ATTRIBUTES_LENGTH_OVERALL_M_FT",
                        "VESSEL_ATTRIBUTES_HULL_MATERIAL_CODE",
                        "VESSEL_ATTRIBUTES_MAIN_ENGINE_1_MAKE",
                        "VESSEL_ATTRIBUTES_MAIN_ENGINE_1_POWER_VALUE",
                        "VESSEL_ATTRIBUTES_MAIN_ENGINE_1_KW_HP_BHP",
                        "VESSEL_ATTRIBUTES_MAIN_ENGINE_2_MAKE",
                        "VESSEL_ATTRIBUTES_MAIN_ENGINE_2_POWER_VALUE",
                        "VESSEL_ATTRIBUTES_MAIN_ENGINE_2_KW_HP_BHP",
                        "VESSEL_ATTRIBUTES_FISH_STORAGE_CAPACITY_VALUE",
                        "VESSEL_ATTRIBUTES_FISH_STORAGE_CAPACITY_T_M3",
                        "VESSEL_ATTRIBUTES_FISH_PRESERVATION_METHODS_METHOD_1_CODE",
                        "VESSEL_ATTRIBUTES_FISH_PRESERVATION_METHODS_METHOD_2_CODE",
                        "VESSEL_ATTRIBUTES_FISH_PRESERVATION_METHODS_METHOD_3_CODE",
                        "VESSEL_ATTRIBUTES_FISH_PRESERVATION_METHODS_METHOD_4_CODE",
                        "VESSEL_ATTRIBUTES_FISH_STORAGE_TYPES_TYPE_1_CODE",
                        "VESSEL_ATTRIBUTES_FISH_STORAGE_TYPES_TYPE_2_CODE",
                        "VESSEL_ATTRIBUTES_FISH_STORAGE_TYPES_TYPE_3_CODE",
                        "VESSEL_ATTRIBUTES_AUTONOMY_RANGE_VALUE",
                        "VESSEL_ATTRIBUTES_AUTONOMY_RANGE_DAYS_NM",
                        "VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_GPS",
                        "VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_VMS",
                        "VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_AIS",
                        "VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_RADARS",
                        "VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_TRACK_PLOTTER",
                        "VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_DEPTH_SOUNDER",
                        "VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_SONAR",
                        "VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_DOPPLER_CURRENT_METER",
                        "VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_XBT",
                        "VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_VHF_RADIOS",
                        "VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_HF_RADIOS",
                        "VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_SATELLITE_COMM",
                        "VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_SST_GAUGE",
                        "VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_WEATHER_FAX",
                        "VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_FIS",
                        "VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_1_CATEGORY_1_CODE	STORAGE_DISPOSAL_METHOD_1_CODE	OTHER_1",
                        "VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_1_STORAGE_DISPOSAL_METHOD_1_CODE	OTHER_1",
                        "VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_1_OTHER_1",
                        "VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_2_CATEGORY_2_CODE	STORAGE_DISPOSAL_METHOD_2_CODE	OTHER_2",
                        "VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_2_STORAGE_DISPOSAL_METHOD_2_CODE	OTHER_2",
                        "VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_2_OTHER_2",
                        "VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_3_CATEGORY_3_CODE	STORAGE_DISPOSAL_METHOD_3_CODE	OTHER_3",
                        "VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_3_STORAGE_DISPOSAL_METHOD_3_CODE	OTHER_3",
                        "VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_3_OTHER_3",
                        "VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_4_CATEGORY_4_CODE	STORAGE_DISPOSAL_METHOD_4_CODE	OTHER_4",
                        "VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_4_STORAGE_DISPOSAL_METHOD_4_CODE	OTHER_4",
                        "VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_4_OTHER_4")

#[ 6] = "G-GENERAL" | From row 6 - 14 columns
G_GENERAL_NAMES <- c("OBSERVED_TRIP_NUMBER",
                     "SPECIAL_EQUIPMENT_OR_MACHINERY_POWER_BLOCK",
                     "SPECIAL_EQUIPMENT_OR_MACHINERY_PURSE_WINCH",
                     "GENERAL_GEAR_ATTRIBUTES_NET_MAX_LENGTH_VALUE",
                     "GENERAL_GEAR_ATTRIBUTES_NET_MAX_LENGTH_M_KM",
                     "GENERAL_GEAR_ATTRIBUTES_NET_MAX_DEPTH_VALUE",
                     "GENERAL_GEAR_ATTRIBUTES_NET_MAX_DEPTH_M_KM",
                     "GENERAL_GEAR_ATTRIBUTES_MESH_SIZE_BUNT_STRETCHED_VALUE",
                     "GENERAL_GEAR_ATTRIBUTES_MESH_SIZE_BUNT_STRETCHED_MM_CM_M",
                     "GENERAL_GEAR_ATTRIBUTES_MESH_SIZE_MID_NET_STRETCHED_VALUE",
                     "GENERAL_GEAR_ATTRIBUTES_MESH_SIZE_MID_NET_STRETCHED_MM_CM_M",
                     "GENERAL_GEAR_ATTRIBUTES_MAX_BRAIL_CAPACITY_VALUE_MT",
                     "GENERAL_GEAR_ATTRIBUTES_SKIFF_POWER_VALUE",
                     "GENERAL_GEAR_ATTRIBUTES_SKIFF_POWER_KW_HP_BHP")

#[ 7] = "E-SET" | From row 6 - 29 columns
E_SET_NAMES <- c("OBSERVED_TRIP_NUMBER",
                 "SET_NUMBER",
                 "SETTING_OPERATIONS_START_SETTING_TIMESTAMP",
                 "SETTING_OPERATIONS_START_SETTING_LATITUDE",
                 "SETTING_OPERATIONS_START_SETTING_LONGITUDE",
                 "SETTING_OPERATIONS_BEAUFORT_SCALE_CODE",
                 "SETTING_OPERATIONS_SCHOOL_SIGHTING_CUES_CUE_1_CODE",
                 "SETTING_OPERATIONS_SCHOOL_SIGHTING_CUES_CUE_2_CODE",
                 "SETTING_OPERATIONS_SCHOOL_SIGHTING_CUES_CUE_3_CODE",
                 "SETTING_OPERATIONS_SCHOOL_SIGHTING_CUES_CUE_4_CODE",
                 "SETTING_OPERATIONS_FIRST_DETECTION_METHOD_CODE",
                 "SETTING_OPERATIONS_SCHOOL_SIZE_T",
                 "SETTING_OPERATIONS_DATE_TIME_NET_PURSED_UTC",
                 "SETTING_OPERATIONS_BRAILING_DATE_TIME_START_UTC",
                 "SETTING_OPERATIONS_BRAILING_DATE_TIME_END_UTC",
                 "SETTING_OPERATIONS_DATE_TIME_SKIFF_ONBOARD_UTC",
                 "SETTING_OPERATIONS_MAXIMUM_CLOSING_NET_DEPTH_M",
                 "SETTING_OPERATIONS_OBJECT_DETAILS_BUOY_ID",
                 "SETTING_OPERATIONS_OBJECT_DETAILS_BUOY_EQUIPPED_WITH_ARTIFICIAL_LIGHTS_AT_DEPLOY",
                 "SETTING_OPERATIONS_OBJECT_DETAILS_BUOY_EQUIPPED_WITH_ARTIFICIAL_LIGHTS_ON_RETRIEVAL",
                 "SETTING_OPERATIONS_OBJECT_DETAILS_ARTIFICIAL_FAD_DESIGN_RAFT_DESIGN_CODE",
                 "SETTING_OPERATIONS_OBJECT_DETAILS_ARTIFICIAL_FAD_DESIGN_TAIL_DESIGN_CODE",
                 "SETTING_OPERATIONS_SUPPORT_VESSEL_DETAILS_PRESENCE",
                 "SETTING_OPERATIONS_SUPPORT_VESSEL_DETAILS_NAME",
                 "SETTING_OPERATIONS_SUPPORT_VESSEL_DETAILS_PARTICIPATION",
                 "SETTING_OPERATIONS_SUPPORT_VESSEL_DETAILS_DESCRIPTION",
                 "SETTING_OPERATIONS_DETAILS_ON_CURRENT_DIRECTION",
                 "SETTING_OPERATIONS_DETAILS_ON_CURRENT_SPEED_KNOTS",
                 "SETTING_OPERATIONS_DETAILS_ON_CURRENT_DEPTH_M")

#[ 8] = "E-SET-CETACEANS" | From row 6 - 6 columns
E_SET_CETACEANS_NAMES <- c("OBSERVED_TRIP_NUMBER",
                           "SET_NUMBER",
                           "SETTING_OPERATIONS_SIGHTING_DETAILS_SIGHTING_BEFORE_SETTING",
                           "SETTING_OPERATIONS_SIGHTING_DETAILS_SPECIES_CODE",
                           "SETTING_OPERATIONS_SIGHTING_DETAILS_NUM_SIGHTED",
                           "SETTING_OPERATIONS_SIGHTING_DETAILS_CAUGHT_INSIDE_NET")

#[ 9] = "E-SET-CATCHES" | From row 6 - 14 columns
E_SET_CATCHES_NAMES <- c("OBSERVED_TRIP_NUMBER",
                         "SET_NUMBER",
                         "CATCH_NUMBER",
                         "CATCH_DETAILS_SPECIES_CODE",
                         "CATCH_DETAILS_FATE_TYPE",
                         "CATCH_DETAILS_FATE_CODE",
                         "CATCH_DETAILS_SAMPLING_METHOD_CODE",
                         "CATCH_DETAILS_NUM_FISH",
                         "CATCH_DETAILS_WEIGHT_PROCESSING_TYPE_CODE",
                         "CATCH_DETAILS_WEIGHT_VALUE",
                         "CATCH_DETAILS_WEIGHT_KG_T",
                         "CATCH_DETAILS_WEIGHT_ESTIMATION_METHOD_CODE",
                         "CATCH_DETAILS_NON_TARGET_SPECIES_ADDITIONAL_DETAILS_CONDITION_AT_CAPTURE_CODE",
                         "CATCH_DETAILS_NON_TARGET_SPECIES_ADDITIONAL_DETAILS_CONDITION_AT_RELEASE_CODE")

#[10] = "E-SET-CATCHES-SPECIMEN" | From row 6 - 29 columns
E_SET_CATCHES_SPECIMEN_NAMES <- c("OBSERVED_TRIP_NUMBER",
                                  "SET_NUMBER",
                                  "CATCH_NUMBER",
                                  "SPECIMEN_NUMBER",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_ADDITIONAL_DETAILS_CONDITION_AT_CAPTURE_CODE",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_ADDITIONAL_DETAILS_CONDITION_AT_RELEASE_CODE",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_LENGTH_1_TYPE_CODE",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_LENGTH_1_VALUE_CM",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_LENGTH_1_MEASURING_TOOL_CODE",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_LENGTH_1_IS_STRAIGHT",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_LENGTH_2_TYPE_CODE",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_LENGTH_2_VALUE_CM",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_LENGTH_2_MEASURING_TOOL_CODE",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_LENGTH_2_IS_STRAIGHT",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_WEIGHT_PROCESSING_TYPE_CODE",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_WEIGHT_VALUE_KG",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_WEIGHT_ESTIMATION_METHOD_CODE",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_SEX",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_MATURITY_SCALE",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_MATURITY_STAGE",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_SAMPLE_COLLECTED_TYPE",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_SAMPLE_COLLECTED_PRESERVATION_METHOD",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_TAG_DETAILS_RELEASE",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_TAG_DETAILS_RECOVERY",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_TAG_DETAILS_TYPE_CODE",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_TAG_DETAILS_TAG_NUMBER_1",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_TAG_DETAILS_TAG_NUMBER_2",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_TAG_DETAILS_FINDER_NAME_AND_CONTACT_DETAILS",
                                  "SPECIMEN_DETAILS_NON_TARGET_SPECIES_TAG_DETAILS_WELL")

#[11] = "E-SET-CATCHES-SPECIMEN-SSI" | From row 6 - 9 columns
E_SET_CATCHES_SPECIMEN_SSI_NAMES <- c("OBSERVED_TRIP_NUMBER",
                                      "SET_NUMBER",
                                      "CATCH_NUMBER",
                                      "SPECIMEN_NUMBER",
                                      "SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_GEAR_INTERACTION_CODE",
                                      "SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_BROUGHT_ONBOARD",
                                      "SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_HANDLING_METHOD_CODE",
                                      "SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_REVIVAL",
                                      "SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_PHOTO_ID")

#[12] = "A-SURFACE" | From row 6 - 6 columns
A_SURFACE_NAMES <- c("OBSERVED_TRIP_NUMBER",
                     "ACTIVITY_DETAILS_DATE_TIME_UTC",
                     "ACTIVITY_DETAILS_LATITUDE",
                     "ACTIVITY_DETAILS_LONGITUDE",
                     "ACTIVITY_DETAILS_ACTIVITY_TYPE_CODE",
                     "ACTIVITY_DETAILS_COMMENTS")

#[13] = "T-EVENTS" | From row 6 - 15 columns
T_EVENTS_NAMES <- c("OBSERVED_TRIP_NUMBER",
                    "TRANSSHIPMENT_NUMBER",
                    "VESSEL_TRANSSHIPMENT_EVENT_START_EVENT_DATE_TIME_UTC",
                    "VESSEL_TRANSSHIPMENT_EVENT_START_EVENT_LATITUDE",
                    "VESSEL_TRANSSHIPMENT_EVENT_START_EVENT_LONGITUDE",
                    "VESSEL_TRANSSHIPMENT_EVENT_END_EVENT_DATE_TIME_UTC",
                    "VESSEL_TRANSSHIPMENT_EVENT_END_EVENT_LATITUDE",
                    "VESSEL_TRANSSHIPMENT_EVENT_END_EVENT_LONGITUDE",
                    "VESSEL_TRANSSHIPMENT_EVENT_CATEGORY_CODE",
                    "VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_NAME",
                    "VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_FLAG_OR_CHARTERING_CODE",
                    "VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_IRCS",
                    "VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_REGISTRATION_COUNTRY_CODE",
                    "VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_REGISTRATION_PORT_CODE",
                    "VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_REGISTRATION_NUMBER")

#[14] = "T-PRODUCTS" | From row 6 - 6 columns
T_PRODUCTS_NAMES <- c("OBSERVED_TRIP_NUMBER",
                      "TRANSSHIPMENT_NUMBER",
                      "PRODUCT_TRANSSHIPPED_SPECIES_CODE",
                      "PRODUCT_TRANSSHIPPED_PROCESSING_TYPE_CODE",
                      "PRODUCT_TRANSSHIPPED_QUANTITY_VALUE",
                      "PRODUCT_TRANSSHIPPED_QUANTITY_KG_T")

SHEETS_COLUMN_NAMES <- list(
  O_INFO_NAMES,
  V_INFO_NAMES,
  V_TRIP_NAMES,
  V_ATTRIBUTES_NAMES,
  G_GENERAL_NAMES,
  E_SET_NAMES,
  E_SET_CETACEANS_NAMES,
  E_SET_CATCHES_NAMES,
  E_SET_CATCHES_SPECIMEN_NAMES,
  E_SET_CATCHES_SPECIMEN_SSI_NAMES,
  A_SURFACE_NAMES,
  T_EVENTS_NAMES,
  T_PRODUCTS_NAMES)

names(SHEETS_COLUMN_NAMES) <- sheets

yata_frame <- lapply(sheets, openxlsx::read.xlsx, xlsxFile = path, colNames = FALSE, skipEmptyCols = FALSE, detectDates = FALSE)

yata <- list()

for (i in seq(1:13)) {
  sheet_name <- as.character(sheets[i])
  print(sheet_name)
  ya <- as.data.table(yata_frame[i])
  if (nrow(ya) < 6) {
    # No data in this sheet
    ya <- NULL
  } else {
    yo <- SHEETS_COLUMN_NAMES[[sheet_name]]
    ya <- ya[6:nrow(ya)]
    names(ya) <- yo
  }
  yata[[sheet_name]] <- ya
}
remove(yo)
remove(ya)
remove(yata_frame)
remove(sheet_name)
