#' The import file model for the ROS version 3.2.1 on Longline domain
#' @export

ROS_3_2_1_LL_IMPORT_MODEL <-
  ImportFile$new("Ros 3.2.1 - LL", c(
    #[ 2] = "O-INFO" | From row 6 - 25 columns
    Sheet$new("O-INFO", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      Column$new("OBSERVER_IDENTIFICATION_OBSERVER_IOTC_NUMBER", mandatory = TRUE),
      Column$new("OBSERVER_IDENTIFICATION_FULL_NAME"),
      ForeignKeyColumn$new("OBSERVER_IDENTIFICATION_NATIONALITY_CODE", foreign_table = "refs_admin.countries", foreign_column = "code"),
      ForeignKeyColumn$new("OBSERVER_TRIP_DETAILS_EMBARKATION_IN_PORT_COUNTRY_CODE", foreign_table = "refs_admin.countries", foreign_column = "code"),
      ForeignKeyColumn$new("OBSERVER_TRIP_DETAILS_EMBARKATION_IN_PORT_PORT_CODE", foreign_table = "refs_admin.ports", foreign_column = "code"),
      Column$new("OBSERVER_TRIP_DETAILS_EMBARKATION_AT_SEA_LATITUDE"),
      Column$new("OBSERVER_TRIP_DETAILS_EMBARKATION_AT_SEA_LONGITUDE"),
      Column$new("OBSERVER_TRIP_DETAILS_EMBARKATION_AT_SEA_TIMESTAMP"),
      ForeignKeyColumn$new("OBSERVER_TRIP_DETAILS_DISEMBARKATION_IN_PORT_COUNTRY_CODE", foreign_table = "refs_admin.countries", foreign_column = "code"),
      ForeignKeyColumn$new("OBSERVER_TRIP_DETAILS_DISEMBARKATION_IN_PORT_PORT_CODE", foreign_table = "refs_admin.ports", foreign_column = "code"),
      Column$new("OBSERVER_TRIP_DETAILS_DISEMBARKATION_AT_SEA_LATITUDE"),
      Column$new("OBSERVER_TRIP_DETAILS_DISEMBARKATION_AT_SEA_LONGITUDE"),
      Column$new("OBSERVER_TRIP_DETAILS_DISEMBARKATION_AT_SEA_TIMESTAMP"),
      Column$new("OBSERVED_TRIP_SUMMARY_NUMBER_OF_SETS_CONDUCTED", mandatory = TRUE),
      Column$new("OBSERVED_TRIP_SUMMARY_NUMBER_OF_SETS_OBSERVED", mandatory = TRUE),
      Column$new("OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_SEARCHING", mandatory = TRUE),
      Column$new("OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_ACTIVELY_FISHING", mandatory = TRUE),
      Column$new("OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_IN_FISHING_AREA"),
      Column$new("OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_TRANSITING"),
      Column$new("OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_LOST", mandatory = TRUE),
      ForeignKeyColumn$new("OBSERVED_TRIP_SUMMARY_REASONS_FOR_DAYS_LOST_REASON_1_CODE", foreign_table = "refs_fishery.reasons_days_lost", foreign_column = "code"),
      ForeignKeyColumn$new("OBSERVED_TRIP_SUMMARY_REASONS_FOR_DAYS_LOST_REASON_2_CODE", foreign_table = "refs_fishery.reasons_days_lost", foreign_column = "code"),
      ForeignKeyColumn$new("OBSERVED_TRIP_SUMMARY_REASONS_FOR_DAYS_LOST_REASON_3_CODE", foreign_table = "refs_fishery.reasons_days_lost", foreign_column = "code"),
      ForeignKeyColumn$new("OBSERVED_TRIP_SUMMARY_REASONS_FOR_DAYS_LOST_REASON_4_CODE", foreign_table = "refs_fishery.reasons_days_lost", foreign_column = "code"))),
    #[ 3] = "V-INFO" | From row 6 - 32 columns
    Sheet$new("V-INFO", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      Column$new("VESSEL_INFORMATION_IDENTIFICATION_NAME", mandatory = TRUE),
      ForeignKeyColumn$new("VESSEL_INFORMATION_IDENTIFICATION_FLAG_OR_CHARTERING_CODE", mandatory = TRUE, foreign_table = "refs_admin.countries", foreign_column = "code"),
      Column$new("VESSEL_INFORMATION_IDENTIFICATION_IOTC_NUMBER", mandatory = TRUE),
      Column$new("VESSEL_INFORMATION_IDENTIFICATION_IMO_NUMBER"),
      Column$new("VESSEL_INFORMATION_IDENTIFICATION_IRCS"),
      ForeignKeyColumn$new("VESSEL_INFORMATION_IDENTIFICATION_REGISTRATION_COUNTRY_CODE", mandatory = TRUE, foreign_table = "refs_admin.countries", foreign_column = "code"),
      ForeignKeyColumn$new("VESSEL_INFORMATION_IDENTIFICATION_REGISTRATION_PORT_CODE", mandatory = TRUE, foreign_table = "refs_admin.ports", foreign_column = "code"),
      Column$new("VESSEL_INFORMATION_IDENTIFICATION_REGISTRATION_NUMBER"),
      Column$new("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_PHONE_1"),
      Column$new("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_PHONE_2"),
      Column$new("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_FAX_1"),
      Column$new("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_FAX_2"),
      Column$new("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_EMAIL_1"),
      Column$new("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_EMAIL_2"),
      ForeignKeyColumn$new("VESSEL_INFORMATION_IDENTIFICATION_LICENSED_TARGET_SPECIES_SPECIES_1_CODE", foreign_table = "refs_biological.species", foreign_column = "code"),
      ForeignKeyColumn$new("VESSEL_INFORMATION_IDENTIFICATION_LICENSED_TARGET_SPECIES_SPECIES_2_CODE", foreign_table = "refs_biological.species", foreign_column = "code"),
      ForeignKeyColumn$new("VESSEL_INFORMATION_IDENTIFICATION_LICENSED_TARGET_SPECIES_SPECIES_3_CODE", foreign_table = "refs_biological.species", foreign_column = "code"),
      ForeignKeyColumn$new("VESSEL_INFORMATION_IDENTIFICATION_LICENSED_TARGET_SPECIES_SPECIES_4_CODE", foreign_table = "refs_biological.species", foreign_column = "code"),
      ForeignKeyColumn$new("VESSEL_INFORMATION_IDENTIFICATION_MAIN_FISHING_GEAR_CODE", mandatory = TRUE, foreign_table = "refs_fishery.gears", foreign_column = "code"),
      Column$new("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_OWNER_FULL_NAME"),
      ForeignKeyColumn$new("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_OWNER_NATIONALITY_CODE", foreign_table = "refs_admin.countries", foreign_column = "code"),
      Column$new("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_OWNER_CONTACT_DETAILS"),
      Column$new("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CHARTER_OR_OPERATOR_FULL_NAME"),
      ForeignKeyColumn$new("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CHARTER_OR_OPERATOR_NATIONALITY_CODE", foreign_table = "refs_admin.countries", foreign_column = "code"),
      Column$new("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CHARTER_OR_OPERATOR_CONTACT_DETAILS"),
      Column$new("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CHARTER_OR_OPERATOR_CONTACT_DETAILS2"),
      Column$new("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_FISHING_MASTER_FULL_NAME"),
      ForeignKeyColumn$new("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_FISHING_MASTER_NATIONALITY_CODE", foreign_table = "refs_admin.countries", foreign_column = "code"),
      Column$new("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_SKIPPER_CAPTAIN_FULL_NAME"),
      ForeignKeyColumn$new("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_SKIPPER_CAPTAIN_NATIONALITY_CODE", foreign_table = "refs_admin.countries", foreign_column = "code"),
      Column$new("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CREW_NUMBER"))),
    #[ 4] = "V-TRIP" | From row 6 - 11 columns
    Sheet$new("V-TRIP", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      ForeignKeyColumn$new("TRIP_DETAILS_VESSEL_DEPARTURE_PORT_COUNTRY_CODE", foreign_table = "refs_admin.countries", foreign_column = "code"),
      ForeignKeyColumn$new("TRIP_DETAILS_VESSEL_DEPARTURE_PORT_PORT_CODE", foreign_table = "refs_admin.ports", foreign_column = "code"),
      Column$new("TRIP_DETAILS_VESSEL_DEPARTURE_PORT_LATITUDE"),
      Column$new("TRIP_DETAILS_VESSEL_DEPARTURE_PORT_LONGITUDE"),
      Column$new("TRIP_DETAILS_VESSEL_DEPARTURE_TIMESTAMP"),
      ForeignKeyColumn$new("TRIP_DETAILS_VESSEL_RETURN_PORT_COUNTRY_CODE", foreign_table = "refs_admin.countries", foreign_column = "code"),
      ForeignKeyColumn$new("TRIP_DETAILS_VESSEL_RETURN_PORT_PORT_CODE", foreign_table = "refs_admin.ports", foreign_column = "code"),
      Column$new("TRIP_DETAILS_VESSEL_RETURN_PORT_LATITUDE"),
      Column$new("TRIP_DETAILS_VESSEL_RETURN_PORT_LONGITUDE"),
      Column$new("TRIP_DETAILS_VESSEL_RETURN_TIMESTAMP"))),
    #[ 5] = "V-ATTRIBUTES" | From row 6 - 50 columns
    Sheet$new("V-ATTRIBUTES", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      MeasurementValueColumn$new("VESSEL_ATTRIBUTES_TONNAGE_VALUE", mandatory = TRUE),
      MeasurementUnitColumn$new("VESSEL_ATTRIBUTES_TONNAGE_GT_GRT", mandatory = TRUE),
      MeasurementValueColumn$new("VESSEL_ATTRIBUTES_LENGTH_OVERALL_VALUE", mandatory = TRUE),
      MeasurementUnitColumn$new("VESSEL_ATTRIBUTES_LENGTH_OVERALL_M_FT", mandatory = TRUE),
      ForeignKeyColumn$new("VESSEL_ATTRIBUTES_HULL_MATERIAL_CODE", mandatory = TRUE, foreign_table = "refs_fishery.hull_material_types", foreign_column = "code"),
      Column$new("VESSEL_ATTRIBUTES_MAIN_ENGINE_1_MAKE", mandatory = TRUE),
      MeasurementValueColumn$new("VESSEL_ATTRIBUTES_MAIN_ENGINE_1_POWER_VALUE", mandatory = TRUE),
      MeasurementUnitColumn$new("VESSEL_ATTRIBUTES_MAIN_ENGINE_1_KW_HP_BHP", mandatory = TRUE),
      Column$new("VESSEL_ATTRIBUTES_MAIN_ENGINE_2_MAKE"),
      MeasurementValueColumn$new("VESSEL_ATTRIBUTES_MAIN_ENGINE_2_POWER_VALUE"),
      MeasurementUnitColumn$new("VESSEL_ATTRIBUTES_MAIN_ENGINE_2_KW_HP_BHP"),
      MeasurementValueColumn$new("VESSEL_ATTRIBUTES_FISH_STORAGE_CAPACITY_VALUE", mandatory = TRUE),
      Column$new("VESSEL_ATTRIBUTES_FISH_STORAGE_CAPACITY_T_M3", mandatory = TRUE),
      ForeignKeyColumn$new("VESSEL_ATTRIBUTES_FISH_PRESERVATION_METHODS_METHOD_1_CODE", foreign_table = "refs_fishery.fish_preservation_methods", foreign_column = "code"),
      ForeignKeyColumn$new("VESSEL_ATTRIBUTES_FISH_PRESERVATION_METHODS_METHOD_2_CODE", foreign_table = "refs_fishery.fish_preservation_methods", foreign_column = "code"),
      ForeignKeyColumn$new("VESSEL_ATTRIBUTES_FISH_PRESERVATION_METHODS_METHOD_3_CODE", foreign_table = "refs_fishery.fish_preservation_methods", foreign_column = "code"),
      ForeignKeyColumn$new("VESSEL_ATTRIBUTES_FISH_PRESERVATION_METHODS_METHOD_4_CODE", foreign_table = "refs_fishery.fish_preservation_methods", foreign_column = "code"),
      ForeignKeyColumn$new("VESSEL_ATTRIBUTES_FISH_STORAGE_TYPES_TYPE_1_CODE", foreign_table = "refs_fishery.fish_storage_types", foreign_column = "code"),
      ForeignKeyColumn$new("VESSEL_ATTRIBUTES_FISH_STORAGE_TYPES_TYPE_2_CODE", foreign_table = "refs_fishery.fish_storage_types", foreign_column = "code"),
      ForeignKeyColumn$new("VESSEL_ATTRIBUTES_FISH_STORAGE_TYPES_TYPE_3_CODE", foreign_table = "refs_fishery.fish_storage_types", foreign_column = "code"),
      MeasurementValueColumn$new("VESSEL_ATTRIBUTES_AUTONOMY_RANGE_VALUE"),
      MeasurementUnitColumn$new("VESSEL_ATTRIBUTES_AUTONOMY_RANGE_DAYS_NM"),
      Column$new("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_GPS", mandatory = TRUE),
      Column$new("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_VMS", mandatory = TRUE),
      Column$new("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_AIS", mandatory = TRUE),
      Column$new("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_RADARS", mandatory = TRUE),
      Column$new("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_TRACK_PLOTTER", mandatory = TRUE),
      Column$new("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_DEPTH_SOUNDER", mandatory = TRUE),
      Column$new("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_SONAR", mandatory = TRUE),
      Column$new("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_DOPPLER_CURRENT_METER", mandatory = TRUE),
      Column$new("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_XBT", mandatory = TRUE),
      Column$new("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_VHF_RADIOS"),
      Column$new("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_HF_RADIOS"),
      Column$new("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_SATELLITE_COMM"),
      Column$new("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_SST_GAUGE"),
      Column$new("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_WEATHER_FAX"),
      Column$new("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_FIS"),
      ForeignKeyColumn$new("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_1_CATEGORY_1_CODE", mandatory = TRUE, foreign_table = "refs_fishery.waste_categories", foreign_column = "code"),
      ForeignKeyColumn$new("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_1_STORAGE_DISPOSAL_METHOD_1_CODE", mandatory = TRUE, foreign_table = "refs_fishery.waste_disposal_methods", foreign_column = "code"),
      Column$new("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_1_OTHER_1"),
      ForeignKeyColumn$new("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_2_CATEGORY_2_CODE", foreign_table = "refs_fishery.waste_categories", foreign_column = "code"),
      ForeignKeyColumn$new("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_2_STORAGE_DISPOSAL_METHOD_2_CODE", foreign_table = "refs_fishery.waste_disposal_methods", foreign_column = "code"),
      Column$new("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_2_OTHER_2"),
      ForeignKeyColumn$new("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_3_CATEGORY_3_CODE", foreign_table = "refs_fishery.waste_categories", foreign_column = "code"),
      ForeignKeyColumn$new("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_3_STORAGE_DISPOSAL_METHOD_3_CODE", foreign_table = "refs_fishery.waste_disposal_methods", foreign_column = "code"),
      Column$new("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_3_OTHER_3"),
      ForeignKeyColumn$new("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_4_CATEGORY_4_CODE", foreign_table = "refs_fishery.waste_categories", foreign_column = "code"),
      ForeignKeyColumn$new("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_4_STORAGE_DISPOSAL_METHOD_4_CODE", foreign_table = "refs_fishery.waste_disposal_methods", foreign_column = "code"),
      Column$new("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_4_OTHER_4"))),
    #[ 6] = "G-GENERAL" | From row 6 - 33 columns
    Sheet$new("G-GENERAL", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      Column$new("SPECIAL_EQUIPMENT_OR_MACHINERY_LINE_SETTER", mandatory = TRUE),
      Column$new("SPECIAL_EQUIPMENT_OR_MACHINERY_LINE_HAULER", mandatory = TRUE),
      Column$new("SPECIAL_EQUIPMENT_OR_MACHINERY_BAIT_CASTING_MACHINE", mandatory = TRUE),
      ForeignKeyColumn$new("GENERAL_GEAR_ATTRIBUTES_MAINLINE_MATERIAL_CODE", mandatory = TRUE, foreign_table = "refs_fishery.line_material_types", foreign_column = "code"),
      MeasurementValueColumn$new("GENERAL_GEAR_ATTRIBUTES_MAINLINE_LENGTH_VALUE", mandatory = TRUE),
      MeasurementUnitColumn$new("GENERAL_GEAR_ATTRIBUTES_MAINLINE_LENGTH_KM_NM", mandatory = TRUE),
      MeasurementValueColumn$new("GENERAL_GEAR_ATTRIBUTES_MAINLINE_DIAMETER_VALUE"),
      MeasurementUnitColumn$new("GENERAL_GEAR_ATTRIBUTES_MAINLINE_DIAMETER_MM_CM"),
      ForeignKeyColumn$new("ADDITIONAL_BRANCHLINE_DETAILS_STORAGE_1_CODE", foreign_table = "refs_fishery.branchline_storages", foreign_column = "code"),
      ForeignKeyColumn$new("ADDITIONAL_BRANCHLINE_DETAILS_STORAGE_2_CODE", foreign_table = "refs_fishery.branchline_storages", foreign_column = "code"),
      ForeignKeyColumn$new("ADDITIONAL_BRANCHLINE_DETAILS_STORAGE_3_CODE", foreign_table = "refs_fishery.branchline_storages", foreign_column = "code"),
      ForeignKeyColumn$new("ADDITIONAL_BRANCHLINE_DETAILS_STORAGE_4_CODE", foreign_table = "refs_fishery.branchline_storages", foreign_column = "code"),
      ForeignKeyColumn$new("MITIGATION_DEVICES_DEVICE_1_CODE", foreign_table = "refs_fishery.mitigation_devices", foreign_column = "code"),
      ForeignKeyColumn$new("MITIGATION_DEVICES_DEVICE_2_CODE", foreign_table = "refs_fishery.mitigation_devices", foreign_column = "code"),
      ForeignKeyColumn$new("MITIGATION_DEVICES_DEVICE_3_CODE", foreign_table = "refs_fishery.mitigation_devices", foreign_column = "code"),
      ForeignKeyColumn$new("MITIGATION_DEVICES_DEVICE_4_CODE", foreign_table = "refs_fishery.mitigation_devices", foreign_column = "code"),
      ForeignKeyColumn$new("MITIGATION_DEVICES_DEVICE_5_CODE", foreign_table = "refs_fishery.mitigation_devices", foreign_column = "code"),
      MeasurementValueColumn$new("TORI_LINE_DETAILS_TORI_LINE_LENGTH_VALUE"),
      MeasurementUnitColumn$new("TORI_LINE_DETAILS_TORI_LINE_LENGTH_M_FT"),
      ForeignKeyColumn$new("TORI_LINE_DETAILS_STREAMER_TYPE_CODE", foreign_table = "refs_fishery.streamer_types", foreign_column = "code"),
      Column$new("TORI_LINE_DETAILS_STREAMER_REACH_SURFACE"),
      MeasurementValueColumn$new("TORI_LINE_DETAILS_STREAMER_LINE_LENGTH_MAX_VALUE"),
      MeasurementUnitColumn$new("TORI_LINE_DETAILS_STREAMER_LINE_LENGTH_MAX_CM_M_FT"),
      MeasurementValueColumn$new("TORI_LINE_DETAILS_STREAMER_LINE_LENGTH_MIN_VALUE"),
      MeasurementUnitColumn$new("TORI_LINE_DETAILS_STREAMER_LINE_LENGTH_MIN_CM_M_FT"),
      Column$new("TORI_LINE_DETAILS_STREAMER_NUMBER_PER_LINE"),
      MeasurementValueColumn$new("TORI_LINE_DETAILS_DISTANCE_BETWEEN_STREAMERS_VALUE"),
      Column$new("TORI_LINE_DETAILS_DISTANCE_BETWEEN_STREAMERS_CM_M_FT"),
      MeasurementValueColumn$new("TORI_LINE_DETAILS_TORI_LINE_ATTACHED_HEIGHT_VALUE"),
      MeasurementUnitColumn$new("TORI_LINE_DETAILS_TORI_LINE_ATTACHED_HEIGHT_CM_M_FT"),
      Column$new("TORI_LINE_DETAILS_TOWED_OBJECTS_NUMBER"),
      Column$new("TORI_LINE_DETAILS_TOWED_OBJECTS_TYPE"))),
    #[ 7] = "G-CONFIG-BRANCHLINES" | From row 6 - 8 columns
    Sheet$new("G-CONFIG-BRANCHLINES", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      Column$new("BRANCHLINE_CONFIGURATIONS_CONFIGURATION_NUMBER", mandatory = TRUE),
      Column$new("BRANCHLINE_CONFIGURATIONS_SECTION_NUMBER", mandatory = TRUE),
      ForeignKeyColumn$new("BRANCHLINE_CONFIGURATIONS_MATERIAL_TYPE_CODE", foreign_table = "refs_fishery.line_material_types", foreign_column = "code"),
      MeasurementValueColumn$new("BRANCHLINE_CONFIGURATIONS_LENGTH_VALUE", mandatory = TRUE),
      MeasurementUnitColumn$new("BRANCHLINE_CONFIGURATIONS_LENGTH_CM_M", mandatory = TRUE),
      MeasurementValueColumn$new("BRANCHLINE_CONFIGURATIONS_DIAMETER_VALUE", mandatory = TRUE),
      MeasurementUnitColumn$new("BRANCHLINE_CONFIGURATIONS_DIAMETER_MM_CM", mandatory = TRUE))),
    #[ 8] = "E-SET" | From row 6 - 24 columns
    Sheet$new("E-SET", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      Column$new("SET_NUMBER", mandatory = TRUE),
      Column$new("SETTING_OPERATIONS_START_SETTING_DATE_TIME_UTC", mandatory = TRUE),
      Column$new("SETTING_OPERATIONS_START_SETTING_LATITUDE", mandatory = TRUE),
      Column$new("SETTING_OPERATIONS_START_SETTING_LONGITUDE", mandatory = TRUE),
      Column$new("SETTING_OPERATIONS_END_SETTING_DATE_TIME_UTC", mandatory = TRUE),
      Column$new("SETTING_OPERATIONS_END_SETTING_LATITUDE"),
      Column$new("SETTING_OPERATIONS_END_SETTING_LONGITUDE"),
      MeasurementValueColumn$new("SETTING_OPERATIONS_SPEED_VESSEL_VALUE_KNOTS", unit = "KNOTS"),
      MeasurementValueColumn$new("SETTING_OPERATIONS_SPEED_LINE_SETTER_VALUE_MS", unit = "MS"),
      MeasurementValueColumn$new("SETTING_OPERATIONS_MAINLINE_LENGTH_VALUE", mandatory = TRUE),
      Column$new("SETTING_OPERATIONS_MAINLINE_LENGTH_KM_NM", mandatory = TRUE),
      Column$new("SETTING_OPERATIONS_CLIP_ON_TIME_BRANCHLINE"),
      Column$new("SETTING_OPERATIONS_CLIP_ON_TIME_BUOYS"),
      Column$new("SETTING_OPERATIONS_NUM_TOTAL_HOOKS_SET", mandatory = TRUE),
      Column$new("SETTING_OPERATIONS_NUM_TOTAL_FLOATS_SET"),
      Column$new("SETTING_OPERATIONS_NUM_HOOKS_BETWEEN_FLOATS"),
      Column$new("SETTING_OPERATIONS_SHARK_LINES_SET", mandatory = TRUE),
      Column$new("SETTING_OPERATIONS_SHARK_LINES_NUM_LINES"),
      ForeignKeyColumn$new("SETTING_OPERATIONS_TARGET_SPECIES_SPECIES_1_CODE", mandatory = TRUE, foreign_table = "refs_biological.species", foreign_column = "code"),
      ForeignKeyColumn$new("SETTING_OPERATIONS_TARGET_SPECIES_SPECIES_2_CODE", foreign_table = "refs_biological.species", foreign_column = "code"),
      ForeignKeyColumn$new("SETTING_OPERATIONS_TARGET_SPECIES_SPECIES_3_CODE", foreign_table = "refs_biological.species", foreign_column = "code"),
      ForeignKeyColumn$new("SETTING_OPERATIONS_TARGET_SPECIES_SPECIES_4_CODE", foreign_table = "refs_biological.species", foreign_column = "code"),
      Column$new("SETTING_OPERATIONS_VMS_ON"))),
    #[ 9] = "E-SET-LIGHTS" | From row 6 - 5 columns
    Sheet$new("E-SET-LIGHTS", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      Column$new("SET_NUMBER", mandatory = TRUE),
      ForeignKeyColumn$new("SETTING_OPERATIONS_ATTACHED_LIGHTS_TYPE_CODE", foreign_table = "refs_fishery.light_types", foreign_column = "code"),
      ForeignKeyColumn$new("SETTING_OPERATIONS_ATTACHED_LIGHTS_COLOR_CODE", foreign_table = "refs_fishery.light_colours", foreign_column = "code"),
      Column$new("SETTING_OPERATIONS_ATTACHED_LIGHTS_NUM_LIGHTS"))),
    #[ 10] = "E-SET-BRANCHLINES" | From row 6 - 4 columns
    Sheet$new("E-SET-BRANCHLINES", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      Column$new("SET_NUMBER", mandatory = TRUE),
      Column$new("SETTING_OPERATIONS_BRANCHLINE_DETAILS_CONFIGURATION_NUMBER"),
      Column$new("SETTING_OPERATIONS_BRANCHLINE_DETAILS_NUM_BRANCHLINES_SET"))),
    #[ 11] = "E-SET-HOOKS" | From row 6 - 5 columns
    Sheet$new("E-SET-HOOKS", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      Column$new("SET_NUMBER", mandatory = TRUE),
      ForeignKeyColumn$new("SETTING_OPERATIONS_HOOKS_DETAILS_TYPE_CODE", mandatory = TRUE, foreign_table = "refs_fishery.hook_types", foreign_column = "code"),
      Column$new("SETTING_OPERATIONS_HOOKS_DETAILS_PERCENTAGE", mandatory = TRUE),
      Column$new("SETTING_OPERATIONS_HOOKS_DETAILS_VARIATIONS"))),
    #[ 12] = "E-SET-BAITS" | From row 6 - 6 columns
    Sheet$new("E-SET-BAITS", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      Column$new("SET_NUMBER", mandatory = TRUE),
      ForeignKeyColumn$new("SETTING_OPERATIONS_BAITS_DETAILS_BAIT_CONDITION_CODE", mandatory = TRUE, foreign_table = "refs_biological.species", foreign_column = "code"), # Not Found
      ForeignKeyColumn$new("SETTING_OPERATIONS_BAITS_DETAILS_BAIT_SPECIES_CODE", mandatory = TRUE, foreign_table = "refs_biological.bait_conditions", foreign_column = "code"),
      Column$new("SETTING_OPERATIONS_BAITS_DETAILS_BAIT_PERCENTAGE", mandatory = TRUE),
      Column$new("SETTING_OPERATIONS_BAITS_DETAILS_BAIT_DYE_COLOUR"))),
    #[13] = "E-SET-MITIGATION-MEASURES" | From row 6 - 14 columns
    Sheet$new("E-SET-MITIGATION-MEASURES", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      Column$new("SET_NUMBER", mandatory = TRUE),
      Column$new("SETTING_OPERATIONS_MITIGATION_MEASURES_NUM_TORI_LINES_DEPLOYED", mandatory = TRUE),
      Column$new("SETTING_OPERATIONS_MITIGATION_MEASURES_MIN_DECK_LIGHTING_USED", mandatory = TRUE),
      Column$new("SETTING_OPERATIONS_MITIGATION_MEASURES_HOOKS_SET_BETWEEN_DUSK_DAWN", mandatory = TRUE),
      Column$new("SETTING_OPERATIONS_MITIGATION_MEASURES_BRANCHLINE_WEIGHTED", mandatory = TRUE),
      MeasurementValueColumn$new("SETTING_OPERATIONS_MITIGATION_MEASURES_AVG_BRANCHLINE_WEIGHT_G", mandatory = TRUE, unit = "G"),
      Column$new("SETTING_OPERATIONS_MITIGATION_MEASURES_PERC_BRANCHLINE_WEIGHTED", mandatory = TRUE),
      MeasurementValueColumn$new("SETTING_OPERATIONS_MITIGATION_MEASURES_HOOK_SINKER_DISTANCE_CM", mandatory = TRUE, unit = "CM"),
      Column$new("SETTING_OPERATIONS_MITIGATION_MEASURES_UNDERWATER_SETTING"),
      ForeignKeyColumn$new("SETTING_OPERATIONS_MITIGATION_MEASURES_OTHER_MITIGATION_MEASURES_USED_MEASURE_1_CODE", foreign_table = "refs_fishery.mitigation_devices", foreign_column = "code"),
      ForeignKeyColumn$new("SETTING_OPERATIONS_MITIGATION_MEASURES_OTHER_MITIGATION_MEASURES_USED_MEASURE_2_CODE", foreign_table = "refs_fishery.mitigation_devices", foreign_column = "code"),
      ForeignKeyColumn$new("SETTING_OPERATIONS_MITIGATION_MEASURES_OTHER_MITIGATION_MEASURES_USED_MEASURE_3_CODE", foreign_table = "refs_fishery.mitigation_devices", foreign_column = "code"),
      ForeignKeyColumn$new("SETTING_OPERATIONS_MITIGATION_MEASURES_OTHER_MITIGATION_MEASURES_USED_MEASURE_4_CODE", foreign_table = "refs_fishery.mitigation_devices", foreign_column = "code"))),
    #[14] = "E-SET-HAULING" | From row 6 - 20 columns
    Sheet$new("E-SET-HAULING", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      Column$new("SET_NUMBER", mandatory = TRUE),
      Column$new("HAULING_OPERATIONS_START_HAULING_DATE_TIME_UTC", mandatory = TRUE),
      Column$new("HAULING_OPERATIONS_START_HAULING_LATITUDE", mandatory = TRUE),
      Column$new("HAULING_OPERATIONS_START_HAULING_LONGITUDE", mandatory = TRUE),
      Column$new("HAULING_OPERATIONS_END_HAULING_DATE_TIME_UTC"),
      Column$new("HAULING_OPERATIONS_END_HAULING_LATITUDE"),
      Column$new("HAULING_OPERATIONS_END_HAULING_LONGITUDE"),
      ForeignKeyColumn$new("HAULING_OPERATIONS_OFFAL_MANAGEMENT", foreign_table = "refs_fishery.offal_management_types", foreign_column = "code"), # Rename to xxx_code
      ForeignKeyColumn$new("HAULING_OPERATIONS_POSITIONS_OF_OFFAL_DISPOSAL_POSITION_1_CODE", foreign_table = "refs_fishery.", foreign_column = "code"),  # Not found
      ForeignKeyColumn$new("HAULING_OPERATIONS_POSITIONS_OF_OFFAL_DISPOSAL_POSITION_2_CODE", foreign_table = "refs_fishery.", foreign_column = "code"),  # Not found
      ForeignKeyColumn$new("HAULING_OPERATIONS_POSITIONS_OF_OFFAL_DISPOSAL_POSITION_3_CODE", foreign_table = "refs_fishery.", foreign_column = "code"),  # Not found
      ForeignKeyColumn$new("HAULING_OPERATIONS_POSITIONS_OF_OFFAL_DISPOSAL_POSITION_4_CODE", foreign_table = "refs_fishery.", foreign_column = "code"),  # Not found
      ForeignKeyColumn$new("HAULING_OPERATIONS_METHODS_TO_STUN_FISH_METHOD_1_CODE", foreign_table = "refs_fishery.stunning_methods", foreign_column = "code"),
      ForeignKeyColumn$new("HAULING_OPERATIONS_METHODS_TO_STUN_FISH_METHOD_2_CODE", foreign_table = "refs_fishery.stunning_methods", foreign_column = "code"),
      ForeignKeyColumn$new("HAULING_OPERATIONS_METHODS_TO_STUN_FISH_METHOD_3_CODE", foreign_table = "refs_fishery.stunning_methods", foreign_column = "code"),
      ForeignKeyColumn$new("HAULING_OPERATIONS_METHODS_TO_STUN_FISH_METHOD_4_CODE", foreign_table = "refs_fishery.stunning_methods", foreign_column = "code"),
      Column$new("HAULING_OPERATIONS_BIRD_SCARING_DEVICE_AT_HAULER"),
      Column$new("HAULING_OPERATIONS_NUM_HOOKS_RETRIEVED_DURING_OBSERVATION", mandatory = TRUE),
      ForeignKeyColumn$new("HAULING_OPERATIONS_SAMPLING_PROTOCOL_CODE", mandatory = TRUE, foreign_table = "refs_biological.sampling_protocols", foreign_column = "code"))),
    #[15] = "E-SET-HAULING-BITEOFFS" | From row 6 - 4 columns
    Sheet$new("E-SET-HAULING-BITEOFFS", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      Column$new("SET_NUMBER", mandatory = TRUE),
      Column$new("HAULING_OPERATIONS_BITEOFFS_DETAILS_BRANCHLINE_CONFIGURATION_NUMBER"),
      Column$new("HAULING_OPERATIONS_BITEOFFS_DETAILS_BRANCHLINE_NUM_BITEOFFS"))),
    #[16] = "E-SET-CATCHES" | From row 6 - 12 columns
    Sheet$new("E-SET-CATCHES", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      Column$new("SET_NUMBER", mandatory = TRUE),
      Column$new("CATCH_NUMBER", mandatory = TRUE),
      ForeignKeyColumn$new("CATCH_DETAILS_SPECIES_CODE", mandatory = TRUE, foreign_table = "refs_biological.species", foreign_column = "code"),
      ForeignKeyColumn$new("CATCH_DETAILS_FATE_TYPE", mandatory = TRUE, foreign_table = "refs_biological.types_of_fate", foreign_column = "code"),
      ForeignKeyColumn$new("CATCH_DETAILS_FATE_CODE", mandatory = TRUE, foreign_table = "refs_biological.fates", foreign_column = "code"),
      ForeignKeyColumn$new("CATCH_DETAILS_SAMPLING_METHOD_CODE", mandatory = TRUE, foreign_table = "refs_biological.sampling_methods_for_catch_estimation", foreign_column = "code"),
      Column$new("CATCH_DETAILS_NUM_FISH"),
      ForeignKeyColumn$new("CATCH_DETAILS_WEIGHT_PROCESSING_TYPE_CODE", foreign_table = "refs_fishery.fish_processing_types", foreign_column = "code"),
      MeasurementValueColumn$new("CATCH_DETAILS_WEIGHT_VALUE"),
      MeasurementUnitColumn$new("CATCH_DETAILS_WEIGHT_KG_T"),
      ForeignKeyColumn$new("CATCH_DETAILS_WEIGHT_ESTIMATION_METHOD_CODE", foreign_table = "refs_biological.", foreign_column = "code"))),  # Not found
    #[17] = "E-SET-CATCHES-SPECIMEN" | From row 6 - 32 columns
    Sheet$new("E-SET-CATCHES-SPECIMEN", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      Column$new("SET_NUMBER", mandatory = TRUE),
      Column$new("CATCH_NUMBER", mandatory = TRUE),
      Column$new("SPECIMEN_NUMBER", mandatory = TRUE),
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ALL_SPECIES_SAMPLING_PERIOD_CODE", mandatory = TRUE, foreign_table = "refs_biological.sampling_periods", foreign_column = "code"),
      ForeignKeyColumn$new("SPECIMEN_DETAILS_NON_TARGET_SPECIES_ADDITIONAL_DETAILS_CONDITION_AT_CAPTURE_CODE", foreign_table = "refs_biological.bait_conditions", foreign_column = "code"), # Link not found
      ForeignKeyColumn$new("SPECIMEN_DETAILS_NON_TARGET_SPECIES_ADDITIONAL_DETAILS_CONDITION_AT_RELEASE_CODE", foreign_table = "refs_biological.bait_conditions", foreign_column = "code"), # Link not found
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ALL_SPECIES_DEPREDATION_DETAILS_DEPREDATION_SOURCE_CODE", foreign_table = "refs_biological.depredation_sources", foreign_column = "code"), # Link not found
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ALL_SPECIES_DEPREDATION_DETAILS_OBSERVED_PREDATOR_CODE", foreign_table = "refs_biological.species", foreign_column = "code"),
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ALL_SPECIES_SAMPLING_METHOD_CODE", mandatory = TRUE, foreign_table = "refs_biological.sampling_methods_for_sampling_collections", foreign_column = "code"),
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_1_TYPE_CODE", mandatory = TRUE, foreign_table = "refs_biological.types_of_measurement", foreign_column = "code"), # Check
      MeasurementValueColumn$new("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_1_VALUE_CM", mandatory = TRUE, unit = "CM"),
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_1_MEASURING_TOOL_CODE", mandatory = TRUE, foreign_table = "refs_biological.measurement_tools", foreign_column = "code"),
      Column$new("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_1_IS_STRAIGHT"),
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_2_TYPE_CODE", foreign_table = "refs_biological.types_of_measurement", foreign_column = "code"),
      MeasurementValueColumn$new("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_2_VALUE_CM", unit = "CM"),
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_2_MEASURING_TOOL_CODE", foreign_table = "refs_biological.measurement_tools", foreign_column = "code"),
      Column$new("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_2_IS_STRAIGHT"),
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ALL_SPECIES_WEIGHT_PROCESSING_TYPE_CODE", foreign_table = "refs_fishery.fish_processing_types", foreign_column = "code"),
      MeasurementValueColumn$new("SPECIMEN_DETAILS_ALL_SPECIES_WEIGHT_VALUE_KG", unit = "KG"),
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ALL_SPECIES_WEIGHT_ESTIMATION_METHOD_CODE", foreign_table = "refs_biological.", foreign_column = "code"), # Not found
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ALL_SPECIES_SEX", foreign_table = "refs_biological.sex", foreign_column = "code"),
      Column$new("SPECIMEN_DETAILS_ALL_SPECIES_MATURITY_SCALE"),
      Column$new("SPECIMEN_DETAILS_ALL_SPECIES_MATURITY_STAGE"),
      Column$new("SPECIMEN_DETAILS_ALL_SPECIES_SAMPLE_COLLECTED_TYPE"),
      Column$new("SPECIMEN_DETAILS_ALL_SPECIES_SAMPLE_COLLECTED_PRESERVATION_METHOD"),
      Column$new("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_RELEASE"),
      Column$new("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_RECOVERY"),
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_TYPE_CODE", foreign_table = "refs_biological.tag_types", foreign_column = "code"),
      Column$new("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_TAG_NUMBER_1"),
      Column$new("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_TAG_NUMBER_2"),
      Column$new("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_FINDER_NAME_AND_CONTACT_DETAILS"))),
    #[18] = "E-SET-CATCHES-SPECIMEN-SSI" | From row 6 - 16 columns
    Sheet$new("E-SET-CATCHES-SPECIMEN-SSI", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      Column$new("SET_NUMBER", mandatory = TRUE),
      Column$new("CATCH_NUMBER", mandatory = TRUE),
      Column$new("SPECIMEN_NUMBER", mandatory = TRUE),
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_GEAR_INTERACTION_CODE", foreign_table = "refs_biological.", foreign_column = "code"),
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_HOOK_TYPE_CODE", foreign_table = "refs_fishery.hook_types", foreign_column = "code"),
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_BAIT_CONDITION_CODE", foreign_table = "refs_biological.bait_conditions", foreign_column = "code"),
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_BAIT_TYPE_CODE", foreign_table = "refs_biological.bait_types", foreign_column = "code"),
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_LEADER_MATERIAL_CODE", foreign_table = "refs_fishery.line_material_types", foreign_column = "code"),
      MeasurementValueColumn$new("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_LEADER_DIAMETER_MM", unit = "MM"),
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_DE_HOOKER_DEVICE_CODE", foreign_table = "refs_fishery.dehooker_types", foreign_column = "code"),
      Column$new("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_LIGHT_ATTACHED"),
      Column$new("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_BROUGHT_ONBOARD"),
      ForeignKeyColumn$new("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_HANDLING_METHOD_CODE", foreign_table = "refs_biological.handling_methods", foreign_column = "code"),
      Column$new("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_REVIVAL"),
      Column$new("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_PHOTO_ID"))),
    #[19] = "T-EVENTS" | From row 6 - 15 columns
    Sheet$new("T-EVENTS", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      Column$new("TRANSSHIPMENT_NUMBER", mandatory = TRUE),
      Column$new("VESSEL_TRANSSHIPMENT_EVENT_START_EVENT_DATE_TIME_UTC"),
      Column$new("VESSEL_TRANSSHIPMENT_EVENT_START_EVENT_LATITUDE"),
      Column$new("VESSEL_TRANSSHIPMENT_EVENT_START_EVENT_LONGITUDE"),
      Column$new("VESSEL_TRANSSHIPMENT_EVENT_END_EVENT_DATE_TIME_UTC"),
      Column$new("VESSEL_TRANSSHIPMENT_EVENT_END_EVENT_LATITUDE"),
      Column$new("VESSEL_TRANSSHIPMENT_EVENT_END_EVENT_LONGITUDE"),
      ForeignKeyColumn$new("VESSEL_TRANSSHIPMENT_EVENT_CATEGORY_CODE", foreign_table = "refs_fishery.transhipment_categories", foreign_column = "code"),
      Column$new("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_NAME"),
      ForeignKeyColumn$new("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_FLAG_OR_CHARTERING_CODE", foreign_table = "refs_admin.countries", foreign_column = "code"),
      Column$new("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_IRCS"),
      ForeignKeyColumn$new("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_REGISTRATION_COUNTRY_CODE", foreign_table = "refs_admin.countries", foreign_column = "code"),
      ForeignKeyColumn$new("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_REGISTRATION_PORT_CODE", foreign_table = "refs_admin.ports", foreign_column = "code"),
      Column$new("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_REGISTRATION_NUMBER"))),
    #[20] = "T-PRODUCTS" | From row 6 - 6 columns
    Sheet$new("T-PRODUCTS", c(
      Column$new("OBSERVED_TRIP_NUMBER", mandatory = TRUE),
      Column$new("TRANSSHIPMENT_NUMBER", mandatory = TRUE),
      ForeignKeyColumn$new("PRODUCT_TRANSSHIPPED_SPECIES_CODE", foreign_table = "refs_biological.species", foreign_column = "code"),
      ForeignKeyColumn$new("PRODUCT_TRANSSHIPPED_PROCESSING_TYPE_CODE", foreign_table = "refs_fishery.fish_processing_types", foreign_column = "code"),
      MeasurementValueColumn$new("PRODUCT_TRANSSHIPPED_QUANTITY_VALUE"),
      MeasurementUnitColumn$new("PRODUCT_TRANSSHIPPED_QUANTITY_KG_T", units = c("KG", "T"))))
  ))

#' Load xls content for Longline domain with ROS model 3.2.1
#'
#' @param path The file to import
#' @return the loaded xls as a list of data.table (one per none empty sheet)
#' @export
load_ll_3_2_1_xls <- function(path) {
  load_xls(path, ROS_3_2_1_LL_IMPORT_MODEL)
}

path <- "/home/tchemit/projects/iotc/2025/ROS_DATA_TO_INPUT/EU-FRANCE/ROS_LL_data_reporting_EU.FRA.REU_2023.xlsx"
taiste <- load_LL_3_2_1_xls(path)
