#' The import file model for the ROS_LL_v3_2_1
#' @export
ROS_LL_v3_2_1_MODEL <-
  import_file("ROS_LL_v3_2_1", c(
    sheet("O-INFO", "#[ 2] = O-INFO | From row 6 - 25 columns", c(
      mandatory_simple_column("OBSERVED_TRIP_NUMBER", column_location("ros_common.general_vessel_and_trip_information", "trip_original_id")),
      mandatory_simple_column("OBSERVER_IDENTIFICATION_OBSERVER_IOTC_NUMBER", column_location("ros_common.observer_identification", "iotc_number")),
      optional_simple_column("OBSERVER_IDENTIFICATION_FULL_NAME", column_location("ros_common.observer_identification", "full_name")),
      ignored_column("OBSERVER_IDENTIFICATION_NATIONALITY_CODE", "Removed in version 3.3.0"),
      optional_fk_column("OBSERVER_TRIP_DETAILS_EMBARKATION_IN_PORT_COUNTRY_CODE", column_location("ros_common.locations", "country_code"), column_location("refs_admin.countries", "code")),
      optional_fk_column("OBSERVER_TRIP_DETAILS_EMBARKATION_IN_PORT_PORT_CODE", column_location("ros_common.locations", "port_code"), column_location("refs_admin.ports", "code")),
      optional_simple_column("OBSERVER_TRIP_DETAILS_EMBARKATION_AT_SEA_LATITUDE", column_location("ros_common.locations", "latitude")),
      optional_simple_column("OBSERVER_TRIP_DETAILS_EMBARKATION_AT_SEA_LONGITUDE", column_location("ros_common.locations", "longitude")),
      optional_simple_column("OBSERVER_TRIP_DETAILS_EMBARKATION_AT_SEA_TIMESTAMP", column_location("ros_common.observer_trip_details", "date_time_embarkation")),
      optional_fk_column("OBSERVER_TRIP_DETAILS_DISEMBARKATION_IN_PORT_COUNTRY_CODE", column_location("ros_common.locations", "country_code"), column_location("refs_admin.countries", "code")),
      optional_fk_column("OBSERVER_TRIP_DETAILS_DISEMBARKATION_IN_PORT_PORT_CODE", column_location("ros_common.locations", "port_code"), column_location("refs_admin.ports", "code")),
      optional_simple_column("OBSERVER_TRIP_DETAILS_DISEMBARKATION_AT_SEA_LATITUDE", column_location("ros_common.locations", "latitude")),
      optional_simple_column("OBSERVER_TRIP_DETAILS_DISEMBARKATION_AT_SEA_LONGITUDE", column_location("ros_common.locations", "longitude")),
      optional_simple_column("OBSERVER_TRIP_DETAILS_DISEMBARKATION_AT_SEA_TIMESTAMP", column_location("ros_common.observer_trip_details", "date_time_disembarkation")),
      mandatory_simple_column("OBSERVED_TRIP_SUMMARY_NUMBER_OF_SETS_CONDUCTED", column_location("ros_common.observed_trip_summary", "number_of_conducted_fishing_events_with_observer_onboard")),
      mandatory_simple_column("OBSERVED_TRIP_SUMMARY_NUMBER_OF_SETS_OBSERVED", column_location("ros_common.observed_trip_summary", "number_of_observed_fishing_events")),
      mandatory_simple_column("OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_SEARCHING", column_location("ros_common.observed_trip_summary", "number_of_days_searching")),
      mandatory_simple_column("OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_ACTIVELY_FISHING", column_location("ros_common.observed_trip_summary", "number_of_active_fishing_days")),
      optional_simple_column("OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_IN_FISHING_AREA", column_location("ros_common.observed_trip_summary", "number_of_days_in_fishing_area")),
      optional_simple_column("OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_TRANSITING", column_location("ros_common.observed_trip_summary", "number_of_days_transiting")),
      mandatory_simple_column("OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_LOST", column_location("ros_common.observed_trip_summary", "number_of_days_lost")),
      optional_fk_column("OBSERVED_TRIP_SUMMARY_REASONS_FOR_DAYS_LOST_REASON_1_CODE", column_location("ros_common.reasons_for_days_lost", "inoperativity_reason"), column_location("refs_fishery.reasons_days_lost", "code")),
      optional_fk_column("OBSERVED_TRIP_SUMMARY_REASONS_FOR_DAYS_LOST_REASON_2_CODE", column_location("ros_common.reasons_for_days_lost", "inoperativity_reason"), column_location("refs_fishery.reasons_days_lost", "code")),
      optional_fk_column("OBSERVED_TRIP_SUMMARY_REASONS_FOR_DAYS_LOST_REASON_3_CODE", column_location("ros_common.reasons_for_days_lost", "inoperativity_reason"), column_location("refs_fishery.reasons_days_lost", "code")),
      optional_fk_column("OBSERVED_TRIP_SUMMARY_REASONS_FOR_DAYS_LOST_REASON_4_CODE", column_location("ros_common.reasons_for_days_lost", "inoperativity_reason"), column_location("refs_fishery.reasons_days_lost", "code")))),
    sheet("V-INFO", "#[ 3] = V-INFO | From row 6 - 32 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      mandatory_simple_column("VESSEL_INFORMATION_IDENTIFICATION_NAME", column_location("ros_common.vessel_identification", "NAME")),
      mandatory_fk_column("VESSEL_INFORMATION_IDENTIFICATION_FLAG_OR_CHARTERING_CODE", column_location("ros_common.vessel_identification", "flag_code"), column_location("refs_admin.countries", "code"), "Fixme : not found"),
      mandatory_simple_column("VESSEL_INFORMATION_IDENTIFICATION_IOTC_NUMBER", column_location("ros_common.vessel_identification", "iotc_number")),
      optional_simple_column("VESSEL_INFORMATION_IDENTIFICATION_IMO_NUMBER", column_location("ros_common.vessel_identification", "imo_number")),
      optional_simple_column("VESSEL_INFORMATION_IDENTIFICATION_IRCS", column_location("ros_common.vessel_identification", "ircs")),
      mandatory_fk_column("VESSEL_INFORMATION_IDENTIFICATION_REGISTRATION_COUNTRY_CODE", column_location("ros_common.vessel_identification", "flag_code"), column_location("refs_admin.countries", "code")),
      optional_fk_column("VESSEL_INFORMATION_IDENTIFICATION_REGISTRATION_PORT_CODE", column_location("ros_common.vessel_identification", "port_code"), column_location("refs_admin.ports", "code")),
      optional_simple_column("VESSEL_INFORMATION_IDENTIFICATION_REGISTRATION_NUMBER", column_location("ros_common.vessel_identification", "registration_number")),
      ignored_column("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_PHONE_1", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_PHONE_2", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_FAX_1", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_FAX_2", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_EMAIL_1", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_EMAIL_2", "Removed in version 3.3.0"),
      optional_fk_column("VESSEL_INFORMATION_IDENTIFICATION_LICENSED_TARGET_SPECIES_SPECIES_1_CODE", column_location("ros_common.vessel_identification_licensed_target_species", "licensed_target_species_code"), column_location("refs_biological.species", "code")),
      optional_fk_column("VESSEL_INFORMATION_IDENTIFICATION_LICENSED_TARGET_SPECIES_SPECIES_2_CODE", column_location("ros_common.vessel_identification_licensed_target_species", "licensed_target_species_code"), column_location("refs_biological.species", "code")),
      optional_fk_column("VESSEL_INFORMATION_IDENTIFICATION_LICENSED_TARGET_SPECIES_SPECIES_3_CODE", column_location("ros_common.vessel_identification_licensed_target_species", "licensed_target_species_code"), column_location("refs_biological.species", "code")),
      optional_fk_column("VESSEL_INFORMATION_IDENTIFICATION_LICENSED_TARGET_SPECIES_SPECIES_4_CODE", column_location("ros_common.vessel_identification_licensed_target_species", "licensed_target_species_code"), column_location("refs_biological.species", "code")),
      mandatory_fk_column("VESSEL_INFORMATION_IDENTIFICATION_MAIN_FISHING_GEAR_CODE", column_location("ros_common.vessel_identification", "main_fishing_gear_code"), column_location("refs_fishery.gears", "code")),
      ignored_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_OWNER_FULL_NAME", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_OWNER_NATIONALITY_CODE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_OWNER_CONTACT_DETAILS", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CHARTER_OR_OPERATOR_FULL_NAME", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CHARTER_OR_OPERATOR_NATIONALITY_CODE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CHARTER_OR_OPERATOR_CONTACT_DETAILS", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CHARTER_OR_OPERATOR_CONTACT_DETAILS2", "Removed in version 3.3.0"),
      mandatory_simple_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_FISHING_MASTER_FULL_NAME", column_location("ros_common.person_details", "full_name")),
      mandatory_fk_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_FISHING_MASTER_NATIONALITY_CODE", column_location("ros_common.person_details", "nationality_code"), column_location("refs_admin.countries", "code")),
      mandatory_simple_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_SKIPPER_CAPTAIN_FULL_NAME", column_location("ros_common.person_details", "full_name")),
      mandatory_fk_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_SKIPPER_CAPTAIN_NATIONALITY_CODE", column_location("ros_common.person_details", "nationality_code"), column_location("refs_admin.countries", "code")),
      optional_simple_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CREW_NUMBER", column_location("ros_common.vessel_owner_and_personnel", "number_of_crew")))),
    sheet("V-TRIP", "#[ 4] = V-TRIP | From row 6 - 11 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("TRIP_DETAILS_VESSEL_DEPARTURE_PORT_COUNTRY_CODE", "Removed in version 3.3.0"),
      optional_fk_column("TRIP_DETAILS_VESSEL_DEPARTURE_PORT_PORT_CODE", column_location("ros_common.vessel_trip_details", "departure_port_code"), column_location("refs_admin.ports", "code")),
      ignored_column("TRIP_DETAILS_VESSEL_DEPARTURE_PORT_LATITUDE", "Removed in version 3.3.0"),
      ignored_column("TRIP_DETAILS_VESSEL_DEPARTURE_PORT_LONGITUDE", "Removed in version 3.3.0"),
      optional_simple_column("TRIP_DETAILS_VESSEL_DEPARTURE_TIMESTAMP", column_location("ros_common.vessel_trip_details", "date_time_vessel_sailed")),
      ignored_column("TRIP_DETAILS_VESSEL_RETURN_PORT_COUNTRY_CODE", "Removed in version 3.3.0"),
      optional_fk_column("TRIP_DETAILS_VESSEL_RETURN_PORT_PORT_CODE", column_location("ros_common.vessel_trip_details", "return_port_code"), column_location("refs_admin.ports", "code")),
      ignored_column("TRIP_DETAILS_VESSEL_RETURN_PORT_LATITUDE", "Removed in version 3.3.0"),
      ignored_column("TRIP_DETAILS_VESSEL_RETURN_PORT_LONGITUDE", "Removed in version 3.3.0"),
      optional_simple_column("TRIP_DETAILS_VESSEL_RETURN_TIMESTAMP", column_location("ros_common.vessel_trip_details", "date_time_vessel_returned_to_port")))),
    sheet("V-ATTRIBUTES", "#[ 5] = V-ATTRIBUTES | From row 6 - 50 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      mandatory_measurement_column("VESSEL_ATTRIBUTES_TONNAGE_VALUE", column_location("ros_common.vessel_attributes", "tonnage_id"), "ros_common.tonnages"),
      mandatory_measurement_unit_column("VESSEL_ATTRIBUTES_TONNAGE_GT_GRT", c("GT", "GRT")),
      mandatory_measurement_column("VESSEL_ATTRIBUTES_LENGTH_OVERALL_VALUE", column_location("ros_common.vessel_attributes", "loa_id"), "ros_common.lengths"),
      mandatory_measurement_unit_column("VESSEL_ATTRIBUTES_LENGTH_OVERALL_M_FT", c("M", "FT")),
      mandatory_fk_column("VESSEL_ATTRIBUTES_HULL_MATERIAL_CODE", column_location("ros_common.vessel_attributes", "hull_material_code"), column_location("refs_fishery.hull_material_types", "code")),
      mandatory_simple_column("VESSEL_ATTRIBUTES_MAIN_ENGINE_1_MAKE", column_location("ros_common.engines", "make")),
      mandatory_measurement_column("VESSEL_ATTRIBUTES_MAIN_ENGINE_1_POWER_VALUE", column_location("ros_common.engines", "value"), "ros_common.engines"),
      mandatory_measurement_unit_column("VESSEL_ATTRIBUTES_MAIN_ENGINE_1_KW_HP_BHP", c("KW", "HP", "BHP")),
      optional_simple_column("VESSEL_ATTRIBUTES_MAIN_ENGINE_2_MAKE", column_location("ros_common.engines", "make")),
      optional_measurement_column("VESSEL_ATTRIBUTES_MAIN_ENGINE_2_POWER_VALUE", column_location("ros_common.engines", "value"), "ros_common.engines"),
      optional_measurement_unit_column("VESSEL_ATTRIBUTES_MAIN_ENGINE_2_KW_HP_BHP", c("KW", "HP", "BHP")),
      mandatory_measurement_column("VESSEL_ATTRIBUTES_FISH_STORAGE_CAPACITY_VALUE", column_location("ros_common.vessel_attributes", "fish_storage_capacity_id"), "ros_common.capacities"),
      optional_measurement_unit_column("VESSEL_ATTRIBUTES_FISH_STORAGE_CAPACITY_T_M3", c("T", "M3")),
      optional_fk_column("VESSEL_ATTRIBUTES_FISH_PRESERVATION_METHODS_METHOD_1_CODE", column_location("ros_common.vessel_attributes_fish_preservation_method", "fish_preservation_method_code"), column_location("refs_fishery.fish_preservation_methods", "code")),
      optional_fk_column("VESSEL_ATTRIBUTES_FISH_PRESERVATION_METHODS_METHOD_2_CODE", column_location("ros_common.vessel_attributes_fish_preservation_method", "fish_preservation_method_code"), column_location("refs_fishery.fish_preservation_methods", "code")),
      optional_fk_column("VESSEL_ATTRIBUTES_FISH_PRESERVATION_METHODS_METHOD_3_CODE", column_location("ros_common.vessel_attributes_fish_preservation_method", "fish_preservation_method_code"), column_location("refs_fishery.fish_preservation_methods", "code")),
      optional_fk_column("VESSEL_ATTRIBUTES_FISH_PRESERVATION_METHODS_METHOD_4_CODE", column_location("ros_common.vessel_attributes_fish_preservation_method", "fish_preservation_method_code"), column_location("refs_fishery.fish_preservation_methods", "code")),
      optional_fk_column("VESSEL_ATTRIBUTES_FISH_STORAGE_TYPES_TYPE_1_CODE", column_location("ros_common.vessel_attributes_fish_storage_type", "fish_storage_type_code"), column_location("refs_fishery.fish_storage_types", "code")),
      optional_fk_column("VESSEL_ATTRIBUTES_FISH_STORAGE_TYPES_TYPE_2_CODE", column_location("ros_common.vessel_attributes_fish_storage_type", "fish_storage_type_code"), column_location("refs_fishery.fish_storage_types", "code")),
      optional_fk_column("VESSEL_ATTRIBUTES_FISH_STORAGE_TYPES_TYPE_3_CODE", column_location("ros_common.vessel_attributes_fish_storage_type", "fish_storage_type_code"), column_location("refs_fishery.fish_storage_types", "code")),
      optional_measurement_column("VESSEL_ATTRIBUTES_AUTONOMY_RANGE_VALUE", column_location("ros_common.vessel_attributes", "autonomy_range_id"), "ros_common.ranges"),
      optional_measurement_unit_column("VESSEL_ATTRIBUTES_AUTONOMY_RANGE_DAYS_NM", c("DAYS", "NM")),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_GPS", column_location("ros_common.vessel_electronics", "gps")),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_VMS", column_location("ros_common.vessel_electronics", "vms")),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_AIS", column_location("ros_common.vessel_electronics", "ais")),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_RADARS", column_location("ros_common.vessel_electronics", "radars")),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_TRACK_PLOTTER", column_location("ros_common.vessel_electronics", "track_plotter")),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_DEPTH_SOUNDER", column_location("ros_common.vessel_electronics", "depth_sounder")),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_SONAR", column_location("ros_common.vessel_electronics", "sonar")),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_DOPPLER_CURRENT_METER", column_location("ros_common.vessel_electronics", "doppler_current_meter")),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_XBT", column_location("ros_common.vessel_electronics", "expendable_bathythermographs")),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_VHF_RADIOS", column_location("ros_common.vessel_electronics", "vhf_radios")),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_HF_RADIOS", column_location("ros_common.vessel_electronics", "hf_radios")),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_SATELLITE_COMM", column_location("ros_common.vessel_electronics", "satellite_communication_systems")),
      ignored_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_SST_GAUGE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_WEATHER_FAX", "Removed in version 3.3.0"),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_FIS", column_location("ros_common.vessel_electronics", "fisheries_information_services")),
      mandatory_fk_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_1_CATEGORY_1_CODE", column_location("ros_common.waste_managements", "waste_category_code"), column_location("refs_fishery.waste_categories", "code")),
      mandatory_fk_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_1_STORAGE_DISPOSAL_METHOD_1_CODE", column_location("ros_common.waste_managements", "waste_storage_or_disposal_method_code"), column_location("refs_fishery.waste_disposal_methods", "code")),
      ignored_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_1_OTHER_1", "Removed in version 3.3.0"),
      optional_fk_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_2_CATEGORY_2_CODE", column_location("ros_common.waste_managements", "waste_category_code"), column_location("refs_fishery.waste_categories", "code")),
      optional_fk_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_2_STORAGE_DISPOSAL_METHOD_2_CODE", column_location("ros_common.waste_managements", "waste_storage_or_disposal_method_code"), column_location("refs_fishery.waste_disposal_methods", "code")),
      ignored_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_2_OTHER_2", "Removed in version 3.3.0"),
      optional_fk_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_3_CATEGORY_3_CODE", column_location("ros_common.waste_managements", "waste_category_code"), column_location("refs_fishery.waste_categories", "code")),
      optional_fk_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_3_STORAGE_DISPOSAL_METHOD_3_CODE", column_location("ros_common.waste_managements", "waste_storage_or_disposal_method_code"), column_location("refs_fishery.waste_disposal_methods", "code")),
      ignored_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_3_OTHER_3", "Removed in version 3.3.0"),
      optional_fk_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_4_CATEGORY_4_CODE", column_location("ros_common.waste_managements", "waste_category_code"), column_location("refs_fishery.waste_categories", "code")),
      optional_fk_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_4_STORAGE_DISPOSAL_METHOD_4_CODE", column_location("ros_common.waste_managements", "waste_storage_or_disposal_method_code"), column_location("refs_fishery.waste_disposal_methods", "code")),
      ignored_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_4_OTHER_4", "Removed in version 3.3.0"))),
    sheet("G-GENERAL", "#[ 6] = G-GENERAL | From row 6 - 33 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      mandatory_simple_column("SPECIAL_EQUIPMENT_OR_MACHINERY_LINE_SETTER", column_location("ros_ll.special_equipment", "line_setter")),
      mandatory_simple_column("SPECIAL_EQUIPMENT_OR_MACHINERY_LINE_HAULER", column_location("ros_ll.special_equipment", "line_hauler")),
      mandatory_simple_column("SPECIAL_EQUIPMENT_OR_MACHINERY_BAIT_CASTING_MACHINE", column_location("ros_ll.special_equipment", "bait_casting_machine")),
      ignored_column("GENERAL_GEAR_ATTRIBUTES_MAINLINE_MATERIAL_CODE", "Removed in version 3.3.0"),
      ignored_column("GENERAL_GEAR_ATTRIBUTES_MAINLINE_LENGTH_VALUE", "Removed in version 3.3.0"),
      ignored_column("GENERAL_GEAR_ATTRIBUTES_MAINLINE_LENGTH_KM_NM", "Removed in version 3.3.0"),
      ignored_column("GENERAL_GEAR_ATTRIBUTES_MAINLINE_DIAMETER_VALUE", "Removed in version 3.3.0"),
      ignored_column("GENERAL_GEAR_ATTRIBUTES_MAINLINE_DIAMETER_MM_CM", "Removed in version 3.3.0"),
      optional_fk_column("ADDITIONAL_BRANCHLINE_DETAILS_STORAGE_1_CODE", column_location("a", "b"), column_location("refs_fishery.branchline_storages", "code"), "Fixme : not found"),
      optional_fk_column("ADDITIONAL_BRANCHLINE_DETAILS_STORAGE_2_CODE", column_location("a", "b"), column_location("refs_fishery.branchline_storages", "code"), "Fixme : not found"),
      optional_fk_column("ADDITIONAL_BRANCHLINE_DETAILS_STORAGE_3_CODE", column_location("a", "b"), column_location("refs_fishery.branchline_storages", "code"), "Fixme : not found"),
      optional_fk_column("ADDITIONAL_BRANCHLINE_DETAILS_STORAGE_4_CODE", column_location("a", "b"), column_location("refs_fishery.branchline_storages", "code"), "Fixme : not found"),
      optional_fk_column("MITIGATION_DEVICES_DEVICE_1_CODE", column_location("ros_ll.gear_specifications_mitigation_device", "mitigation_device_code"), column_location("refs_fishery.mitigation_devices", "code")),
      optional_fk_column("MITIGATION_DEVICES_DEVICE_2_CODE", column_location("ros_ll.gear_specifications_mitigation_device", "mitigation_device_code"), column_location("refs_fishery.mitigation_devices", "code")),
      optional_fk_column("MITIGATION_DEVICES_DEVICE_3_CODE", column_location("ros_ll.gear_specifications_mitigation_device", "mitigation_device_code"), column_location("refs_fishery.mitigation_devices", "code")),
      optional_fk_column("MITIGATION_DEVICES_DEVICE_4_CODE", column_location("ros_ll.gear_specifications_mitigation_device", "mitigation_device_code"), column_location("refs_fishery.mitigation_devices", "code")),
      optional_fk_column("MITIGATION_DEVICES_DEVICE_5_CODE", column_location("ros_ll.gear_specifications_mitigation_device", "mitigation_device_code"), column_location("refs_fishery.mitigation_devices", "code")),
      optional_measurement_column("TORI_LINE_DETAILS_TORI_LINE_LENGTH_VALUE", column_location("ros_ll.tori_line_details", "tori_line_length_id"), "ros_common.lengths"),
      optional_measurement_unit_column("TORI_LINE_DETAILS_TORI_LINE_LENGTH_M_FT", c("M", "FT")),
      optional_fk_column("TORI_LINE_DETAILS_STREAMER_TYPE_CODE", column_location("ros_ll.tori_line_details", "streamer_type"), column_location("refs_fishery.streamer_types", "code")),
      optional_simple_column("TORI_LINE_DETAILS_STREAMER_REACH_SURFACE", column_location("ros_ll.tori_line_details", "streamers_reach_surface")),
      optional_measurement_column("TORI_LINE_DETAILS_STREAMER_LINE_LENGTH_MAX_VALUE", column_location("ros_ll.tori_line_details", "streamer_line_length_max_id"), "ros_common.lengths"),
      optional_measurement_unit_column("TORI_LINE_DETAILS_STREAMER_LINE_LENGTH_MAX_CM_M_FT", c("CM", "M", "FT")),
      optional_measurement_column("TORI_LINE_DETAILS_STREAMER_LINE_LENGTH_MIN_VALUE", column_location("ros_ll.tori_line_details", "streamer_line_length_min_id"), "ros_common.lengths"),
      optional_measurement_unit_column("TORI_LINE_DETAILS_STREAMER_LINE_LENGTH_MIN_CM_M_FT", c("CM", "M", "FT")),
      optional_simple_column("TORI_LINE_DETAILS_STREAMER_NUMBER_PER_LINE", column_location("ros_ll.tori_line_details", "number_of_streamers_per_line")),
      optional_measurement_column("TORI_LINE_DETAILS_DISTANCE_BETWEEN_STREAMERS_VALUE", column_location("ros_ll.tori_line_details", "streamer_distance_id"), "ros_common.distances"),
      optional_measurement_unit_column("TORI_LINE_DETAILS_DISTANCE_BETWEEN_STREAMERS_CM_M_FT", c("CM", "M", "FT")),
      optional_measurement_column("TORI_LINE_DETAILS_TORI_LINE_ATTACHED_HEIGHT_VALUE", column_location("ros_ll.tori_line_details", "attached_height_id"), "ros_common.heights"),
      optional_measurement_unit_column("TORI_LINE_DETAILS_TORI_LINE_ATTACHED_HEIGHT_CM_M_FT", c("CM", "M", "FT")),
      optional_simple_column("TORI_LINE_DETAILS_TOWED_OBJECTS_NUMBER", column_location("ros_ll.tori_line_details", "towed_objects_number")),
      optional_simple_column("TORI_LINE_DETAILS_TOWED_OBJECTS_TYPE", column_location("ros_ll.tori_line_details", "towed_objects_type")))),
    sheet("G-CONFIG-BRANCHLINES", "#[ 7] = G-CONFIG-BRANCHLINES | From row 6 - 8 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      mandatory_simple_column("BRANCHLINE_CONFIGURATIONS_CONFIGURATION_NUMBER", column_location("ros_ll.branchline_configurations", "configuration_original_id")),
      mandatory_simple_column("BRANCHLINE_CONFIGURATIONS_SECTION_NUMBER", column_location("ros_ll.branchline_sections", "section_number")),
      optional_fk_column("BRANCHLINE_CONFIGURATIONS_MATERIAL_TYPE_CODE", column_location("ros_ll.branchline_sections", "branchline_material_type_code"), column_location("refs_fishery.line_material_types", "code")),
      mandatory_measurement_column("BRANCHLINE_CONFIGURATIONS_LENGTH_VALUE", column_location("ros_ll.branchline_sections", "length_id"), "ros_common.lengths"),
      mandatory_measurement_unit_column("BRANCHLINE_CONFIGURATIONS_LENGTH_CM_M", c("CM", "M")),
      mandatory_measurement_column("BRANCHLINE_CONFIGURATIONS_DIAMETER_VALUE", column_location("ros_ll.branchline_sections", "diameter_id"), "ros_common.diameters"),
      mandatory_measurement_unit_column("BRANCHLINE_CONFIGURATIONS_DIAMETER_MM_CM", c("MM", "CM")))),
    sheet("E-SET", "#[ 8] = E-SET | From row 6 - 24 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      mandatory_simple_column("SET_NUMBER", column_location("ros_ll.fishing_events", "event_original_id")),
      mandatory_simple_column("SETTING_OPERATIONS_START_SETTING_DATE_TIME_UTC", column_location("ros_ll.setting_operations", "start_setting_date_and_time")),
      mandatory_simple_column("SETTING_OPERATIONS_START_SETTING_LATITUDE", column_location("ros_ll.setting_operations", "start_setting_latitude")),
      mandatory_simple_column("SETTING_OPERATIONS_START_SETTING_LONGITUDE", column_location("ros_ll.setting_operations", "start_setting_longitude")),
      mandatory_simple_column("SETTING_OPERATIONS_END_SETTING_DATE_TIME_UTC", column_location("ros_ll.setting_operations", "end_setting_date_and_time")),
      mandatory_simple_column("SETTING_OPERATIONS_END_SETTING_LATITUDE", column_location("ros_ll.setting_operations", "end_setting_latitude")),
      mandatory_simple_column("SETTING_OPERATIONS_END_SETTING_LONGITUDE", column_location("ros_ll.setting_operations", "end_setting_longitude")),
      mandatory_simple_column("SETTING_OPERATIONS_SPEED_VESSEL_VALUE_KNOTS", column_location("ros_ll.setting_operations", "vessel_speed")),
      mandatory_simple_column("SETTING_OPERATIONS_SPEED_LINE_SETTER_VALUE_MS", column_location("ros_ll.setting_operations", "line_setter_speed")),
      mandatory_measurement_column("SETTING_OPERATIONS_MAINLINE_LENGTH_VALUE", column_location("ros_ll.setting_operations", "mainline_set_length_id"), "ros_common.lengths"),
      mandatory_measurement_unit_column("SETTING_OPERATIONS_MAINLINE_LENGTH_KM_NM", c("KM", "NM")),
      optional_simple_column("SETTING_OPERATIONS_CLIP_ON_TIME_BRANCHLINE", column_location("ros_ll.setting_operations", "branchline_clip_on_time")),
      optional_simple_column("SETTING_OPERATIONS_CLIP_ON_TIME_BUOYS", column_location("ros_ll.setting_operations", "buoys_clip_on_time")),
      mandatory_simple_column("SETTING_OPERATIONS_NUM_TOTAL_HOOKS_SET", column_location("ros_ll.setting_operations", "total_number_of_hooks_set")),
      optional_simple_column("SETTING_OPERATIONS_NUM_TOTAL_FLOATS_SET", column_location("ros_ll.setting_operations", "total_number_of_floats_set")),
      mandatory_simple_column("SETTING_OPERATIONS_NUM_HOOKS_BETWEEN_FLOATS", column_location("ros_ll.setting_operations", "number_of_hooks_set_between_floats")),
      mandatory_simple_column("SETTING_OPERATIONS_SHARK_LINES_SET", column_location("ros_ll.setting_operations", "shark_lines_set")),
      optional_simple_column("SETTING_OPERATIONS_SHARK_LINES_NUM_LINES", column_location("ros_ll.setting_operations", "number_of_shark_lines_set")),
      mandatory_fk_column("SETTING_OPERATIONS_TARGET_SPECIES_SPECIES_1_CODE", column_location("ros_ll.setting_operations_target_species", "target_species_code"), column_location("refs_biological.species", "code")),
      optional_fk_column("SETTING_OPERATIONS_TARGET_SPECIES_SPECIES_2_CODE", column_location("ros_ll.setting_operations_target_species", "target_species_code"), column_location("refs_biological.species", "code")),
      optional_fk_column("SETTING_OPERATIONS_TARGET_SPECIES_SPECIES_3_CODE", column_location("ros_ll.setting_operations_target_species", "target_species_code"), column_location("refs_biological.species", "code")),
      optional_fk_column("SETTING_OPERATIONS_TARGET_SPECIES_SPECIES_4_CODE", column_location("ros_ll.setting_operations_target_species", "target_species_code"), column_location("refs_biological.species", "code")),
      ignored_column("SETTING_OPERATIONS_VMS_ON", "Removed in version 3.3.0"))),
    sheet("E-SET-LIGHTS", "#[ 9] = E-SET-LIGHTS | From row 6 - 5 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      optional_fk_column("SETTING_OPERATIONS_ATTACHED_LIGHTS_TYPE_CODE", column_location("ros_ll.lights_by_type_and_colour", "light_type_code"), column_location("refs_fishery.light_types", "code")),
      optional_fk_column("SETTING_OPERATIONS_ATTACHED_LIGHTS_COLOR_CODE", column_location("ros_ll.lights_by_type_and_colour", "light_colour_code"), column_location("refs_fishery.light_colours", "code")),
      optional_simple_column("SETTING_OPERATIONS_ATTACHED_LIGHTS_NUM_LIGHTS", column_location("ros_ll.lights_by_type_and_colour", "number_of_lights_by_type_and_colour")))),
    sheet("E-SET-BRANCHLINES", "#[ 10] = E-SET-BRANCHLINES | From row 6 - 4 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      optional_simple_column("SETTING_OPERATIONS_BRANCHLINE_DETAILS_CONFIGURATION_NUMBER", column_location("ros_ll.branchlines_set", "branchline_configuration_original_id")),
      optional_simple_column("SETTING_OPERATIONS_BRANCHLINE_DETAILS_NUM_BRANCHLINES_SET", column_location("ros_ll.branchlines_set", "number_of_branchlines")))),
    sheet("E-SET-HOOKS", "#[ 11] = E-SET-HOOKS | From row 6 - 5 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      mandatory_fk_column("SETTING_OPERATIONS_HOOKS_DETAILS_TYPE_CODE", column_location("ros_ll.hooks_by_type", "hook_type_code"), column_location("refs_fishery.hook_types", "code")),
      optional_simple_column("SETTING_OPERATIONS_HOOKS_DETAILS_PERCENTAGE", column_location("ros_ll.hooks_by_type", "percentage_of_set")),
      optional_simple_column("SETTING_OPERATIONS_HOOKS_DETAILS_VARIATIONS", column_location("ros_ll.hooks_by_type", "variations")))),
    sheet("E-SET-BAITS", "#[ 12] = E-SET-BAITS | From row 6 - 6 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      mandatory_fk_column("SETTING_OPERATIONS_BAITS_DETAILS_BAIT_CONDITION_CODE", column_location("ros_ll.baits_by_conditions", "bait_condition_code"), column_location("refs_biological.bait_conditions", "code")),
      mandatory_fk_column("SETTING_OPERATIONS_BAITS_DETAILS_BAIT_SPECIES_CODE", column_location("ros_ll.baits_by_conditions", "species_code"), column_location("refs_biological.species", "code")),
      mandatory_simple_column("SETTING_OPERATIONS_BAITS_DETAILS_BAIT_PERCENTAGE", column_location("ros_ll.baits_by_conditions", "ratio")),
      optional_simple_column("SETTING_OPERATIONS_BAITS_DETAILS_BAIT_DYE_COLOUR", column_location("ros_ll.baits_by_conditions", "dye_colour")))),
    sheet("E-SET-MITIGATION-MEASURES", "#[13] = E-SET-MITIGATION-MEASURES | From row 6 - 14 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      mandatory_simple_column("SETTING_OPERATIONS_MITIGATION_MEASURES_NUM_TORI_LINES_DEPLOYED", column_location("ros_ll.mitigation_measures", "number_of_tori_lines_deployed")),
      mandatory_simple_column("SETTING_OPERATIONS_MITIGATION_MEASURES_MIN_DECK_LIGHTING_USED", column_location("ros_ll.mitigation_measures", "minimum_deck_lighting_used")),
      mandatory_simple_column("SETTING_OPERATIONS_MITIGATION_MEASURES_HOOKS_SET_BETWEEN_DUSK_DAWN", column_location("ros_ll.mitigation_measures", "hooks_set_between_dusk_and_dawn")),
      optional_simple_column("SETTING_OPERATIONS_MITIGATION_MEASURES_BRANCHLINE_WEIGHTED", column_location("ros_ll.mitigation_measures", "branchline_weighted")),
      mandatory_measurement_column("SETTING_OPERATIONS_MITIGATION_MEASURES_AVG_BRANCHLINE_WEIGHT_G", column_location("ros_ll.mitigation_measures", "average_sinker_weight_id"), "ros_common.weights", "G"),
      mandatory_simple_column("SETTING_OPERATIONS_MITIGATION_MEASURES_PERC_BRANCHLINE_WEIGHTED", column_location("ros_ll.mitigation_measures", "percentage_of_branchlines_weighted")),
      mandatory_measurement_column("SETTING_OPERATIONS_MITIGATION_MEASURES_HOOK_SINKER_DISTANCE_CM", column_location("ros_ll.mitigation_measures", "hook_sinker_distance_id"), "ros_common.distances", "CM"),
      mandatory_simple_column("SETTING_OPERATIONS_MITIGATION_MEASURES_UNDERWATER_SETTING", column_location("ros_ll.mitigation_measures", "hooks_pods")),
      mandatory_fk_column("SETTING_OPERATIONS_MITIGATION_MEASURES_OTHER_MITIGATION_MEASURES_USED_MEASURE_1_CODE", column_location("ros_ll.mitigation_measures_mitigation_devices", "mitigation_device_code"), column_location("refs_fishery.mitigation_devices", "code")),
      mandatory_fk_column("SETTING_OPERATIONS_MITIGATION_MEASURES_OTHER_MITIGATION_MEASURES_USED_MEASURE_2_CODE", column_location("ros_ll.mitigation_measures_mitigation_devices", "mitigation_device_code"), column_location("refs_fishery.mitigation_devices", "code")),
      mandatory_fk_column("SETTING_OPERATIONS_MITIGATION_MEASURES_OTHER_MITIGATION_MEASURES_USED_MEASURE_3_CODE", column_location("ros_ll.mitigation_measures_mitigation_devices", "mitigation_device_code"), column_location("refs_fishery.mitigation_devices", "code")),
      mandatory_fk_column("SETTING_OPERATIONS_MITIGATION_MEASURES_OTHER_MITIGATION_MEASURES_USED_MEASURE_4_CODE", column_location("ros_ll.mitigation_measures_mitigation_devices", "mitigation_device_code"), column_location("refs_fishery.mitigation_devices", "code")))),
    sheet("E-SET-HAULING", "#[14] = E-SET-HAULING | From row 6 - 20 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      mandatory_simple_column("HAULING_OPERATIONS_START_HAULING_DATE_TIME_UTC", column_location("ros_ll.hauling_operations", "start_hauling_date_and_time")),
      mandatory_simple_column("HAULING_OPERATIONS_START_HAULING_LATITUDE", column_location("ros_ll.hauling_operations", "start_hauling_latitude")),
      mandatory_simple_column("HAULING_OPERATIONS_START_HAULING_LONGITUDE", column_location("ros_ll.hauling_operations", "start_hauling_longitude")),
      mandatory_simple_column("HAULING_OPERATIONS_END_HAULING_DATE_TIME_UTC", column_location("ros_ll.hauling_operations", "end_hauling_date_and_time")),
      mandatory_simple_column("HAULING_OPERATIONS_END_HAULING_LATITUDE", column_location("ros_ll.hauling_operations", "end_hauling_latitude")),
      mandatory_simple_column("HAULING_OPERATIONS_END_HAULING_LONGITUDE", column_location("ros_ll.hauling_operations", "end_hauling_longitude")),
      optional_simple_column("HAULING_OPERATIONS_OFFAL_MANAGEMENT", column_location("ros_ll.hauling_operations", "offal_management")),
      optional_simple_column("HAULING_OPERATIONS_POSITIONS_OF_OFFAL_DISPOSAL_POSITION_1_CODE", column_location("ros_ll.hauling_offal_disposal_positions", "offal_disposal_position")),
      optional_simple_column("HAULING_OPERATIONS_POSITIONS_OF_OFFAL_DISPOSAL_POSITION_2_CODE", column_location("ros_ll.hauling_offal_disposal_positions", "offal_disposal_position")),
      optional_simple_column("HAULING_OPERATIONS_POSITIONS_OF_OFFAL_DISPOSAL_POSITION_3_CODE", column_location("ros_ll.hauling_offal_disposal_positions", "offal_disposal_position")),
      optional_simple_column("HAULING_OPERATIONS_POSITIONS_OF_OFFAL_DISPOSAL_POSITION_4_CODE", column_location("ros_ll.hauling_offal_disposal_positions", "offal_disposal_position")),
      ignored_column("HAULING_OPERATIONS_METHODS_TO_STUN_FISH_METHOD_1_CODE", "Removed in version 3.3.0"),
      ignored_column("HAULING_OPERATIONS_METHODS_TO_STUN_FISH_METHOD_2_CODE", "Removed in version 3.3.0"),
      ignored_column("HAULING_OPERATIONS_METHODS_TO_STUN_FISH_METHOD_3_CODE", "Removed in version 3.3.0"),
      ignored_column("HAULING_OPERATIONS_METHODS_TO_STUN_FISH_METHOD_4_CODE", "Removed in version 3.3.0"),
      mandatory_simple_column("HAULING_OPERATIONS_BIRD_SCARING_DEVICE_AT_HAULER", column_location("ros_ll.hauling_operations", "bird_scaring_device_at_hauler")),
      mandatory_simple_column("HAULING_OPERATIONS_NUM_HOOKS_RETRIEVED_DURING_OBSERVATION", column_location("ros_ll.hauling_operations", "number_of_hooks_observed")),
      mandatory_fk_column("HAULING_OPERATIONS_SAMPLING_PROTOCOL_CODE", column_location("ros_ll.hauling_operations", "sampling_protocol_code"), column_location("refs_biological.sampling_protocols", "code")))),
    sheet("E-SET-HAULING-BITEOFFS", "#[15] = E-SET-HAULING-BITEOFFS | From row 6 - 4 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      optional_simple_column("HAULING_OPERATIONS_BITEOFFS_DETAILS_BRANCHLINE_CONFIGURATION_NUMBER", column_location("ros_ll.biteoffs_by_branchlines_set", "branchline_configuration_original_id")),
      optional_simple_column("HAULING_OPERATIONS_BITEOFFS_DETAILS_BRANCHLINE_NUM_BITEOFFS", column_location("ros_ll.biteoffs_by_branchlines_set", "number_of_biteoffs")))),
    sheet("E-SET-CATCHES", "#[16] = E-SET-CATCHES | From row 6 - 12 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      mandatory_simple_column("CATCH_NUMBER", column_location("ros_ll.catch_details", "catch_detail_original_id")),
      mandatory_fk_column("CATCH_DETAILS_SPECIES_CODE", column_location("ros_ll.catch_details", "species_code"), column_location("refs_biological.species", "code")),
      mandatory_fk_column("CATCH_DETAILS_FATE_TYPE", column_location("ros_ll.catch_details", "type_of_fate_code"), column_location("refs_biological.types_of_fate", "code")),
      mandatory_fk_column("CATCH_DETAILS_FATE_CODE", column_location("ros_ll.catch_details", "fates_code"), column_location("refs_biological.fates", "code")),
      mandatory_fk_column("CATCH_DETAILS_SAMPLING_METHOD_CODE", column_location("ros_ll.catch_details", "estimated_weight_sampling_method_code"), column_location("refs_biological.sampling_methods_for_catch_estimation", "code")),
      mandatory_simple_column("CATCH_DETAILS_NUM_FISH", column_location("ros_ll.catch_details", "estimated_catch_in_numbers")),
      optional_fk_column("CATCH_DETAILS_WEIGHT_PROCESSING_TYPE_CODE", column_location("ros_common.estimated_weights", "processing_type_code"), column_location("refs_fishery.fish_processing_types", "code")),
      optional_measurement_column("CATCH_DETAILS_WEIGHT_VALUE", column_location("ros_ll.catch_details", "estimated_weight_id"), "ros_common.estimated_weights"),
      optional_measurement_unit_column("CATCH_DETAILS_WEIGHT_KG_T", c("KG", "T")),
      optional_fk_column("CATCH_DETAILS_WEIGHT_ESTIMATION_METHOD_CODE", column_location("ros_common.estimated_weights", "weight_estimation_method_code"), column_location("refs_biological.sampling_methods_for_catch_estimation", "code")))),
    sheet("E-SET-CATCHES-SPECIMEN", "#[17] = E-SET-CATCHES-SPECIMEN | From row 6 - 32 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      ignored_column("CATCH_NUMBER", "Not used here"),
      mandatory_simple_column("SPECIMEN_NUMBER", column_location("ros_ll.specimens", "specimen_original_id")),
      mandatory_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_SAMPLING_PERIOD_CODE", column_location("ros_ll.specimens", "b"), column_location("refs_biological.sampling_periods", "code")),
      mandatory_fk_column("SPECIMEN_DETAILS_NON_TARGET_SPECIES_ADDITIONAL_DETAILS_CONDITION_AT_CAPTURE_CODE", column_location("ros_common.additional_details_on_non_target_species", "condition_at_capture_code"), column_location("refs_biological.incidental_captures_conditions", "code")),
      mandatory_fk_column("SPECIMEN_DETAILS_NON_TARGET_SPECIES_ADDITIONAL_DETAILS_CONDITION_AT_RELEASE_CODE", column_location("ros_common.additional_details_on_non_target_species", "condition_at_release_code"), column_location("refs_biological.incidental_captures_conditions", "code")),
      optional_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_DEPREDATION_DETAILS_DEPREDATION_SOURCE_CODE", column_location("ros_common.depredation_details", "depredation_source_code"), column_location("refs_biological.scars", "code"), "Fixme : why not using refs_biological.depredation_sources"),
      optional_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_DEPREDATION_DETAILS_OBSERVED_PREDATOR_CODE", column_location("ros_common.depredation_details", "predator_observed_code"), column_location("refs_biological.species", "code")),
      mandatory_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_SAMPLING_METHOD_CODE", column_location("ros_common.biometric_information", "bio_collection_sampling_method_code"), column_location("refs_biological.sampling_methods_for_sampling_collections", "code")),
      mandatory_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_1_TYPE_CODE", column_location("ros_common.measured_lengths", "type_of_measurement_code"), column_location("refs_biological.types_of_measurement", "code")),
      mandatory_measurement_column("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_1_VALUE_CM", column_location("ros_common.measured_lengths", "value"), "ros_common.measured_lengths", "CM"),
      mandatory_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_1_MEASURING_TOOL_CODE", column_location("ros_common.measured_lengths", "length_measuring_tool_code"), column_location("refs_biological.measurement_tools", "code")),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_1_IS_STRAIGHT", column_location("ros_common.measured_lengths", "straight")),
      optional_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_2_TYPE_CODE", column_location("ros_common.measured_lengths", "type_of_measurement_code"), column_location("refs_biological.types_of_measurement", "code")),
      optional_measurement_column("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_2_VALUE_CM", column_location("ros_common.measured_lengths", "value"), "ros_common.measured_lengths", "CM"),
      optional_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_2_MEASURING_TOOL_CODE", column_location("ros_common.measured_lengths", "length_measuring_tool_code"), column_location("refs_biological.measurement_tools", "code")),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_2_IS_STRAIGHT", column_location("ros_common.measured_lengths", "straight")),
      optional_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_WEIGHT_PROCESSING_TYPE_CODE", column_location("ros_common.estimated_weights", "processing_type_code"), column_location("refs_fishery.fish_processing_types", "code")),
      optional_measurement_column("SPECIMEN_DETAILS_ALL_SPECIES_WEIGHT_VALUE_KG", column_location("ros_common.estimated_weights", "value"), "ros_common.estimated_weights", "KG"),
      optional_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_WEIGHT_ESTIMATION_METHOD_CODE", column_location("ros_common.estimated_weights", "weight_estimation_method_code"), column_location("refs_biological.", "code")),
      optional_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_SEX", column_location("ros_common.biometric_information", "sex_code"), column_location("refs_biological.sex", "code")),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_MATURITY_SCALE", column_location("ros_common.maturity_stages", "scale")),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_MATURITY_STAGE", column_location("ros_common.maturity_stages", "maturity_level")),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_SAMPLE_COLLECTED_TYPE", column_location("ros_common.sample_collection_details", "sample_type")),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_SAMPLE_COLLECTED_PRESERVATION_METHOD", column_location("ros_common.sample_collection_details", "preservation_method")),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_RELEASE", column_location("ros_ll.tag_details", "tag_release")),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_RECOVERY", column_location("ros_ll.tag_details", "tag_recovery")),
      optional_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_TYPE_CODE", column_location("ros_ll.tag_details", "tag_type_code"), column_location("refs_biological.tag_types", "code")),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_TAG_NUMBER_1", column_location("ros_ll.tag_details", "tag_original_id")),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_TAG_NUMBER_2", column_location("ros_ll.tag_details", "alternate_tag_original_id")),
      optional_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_FINDER_NAME_AND_CONTACT_DETAILS", column_location("ros_ll.tag_details", "tag_finder_id"), column_location("ros_common.person_contact_details", "id")))),
    sheet("E-SET-CATCHES-SPECIMEN-SSI", "#[18] = E-SET-CATCHES-SPECIMEN-SSI | From row 6 - 16 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      ignored_column("CATCH_NUMBER", "Not used here"),
      ignored_column("SPECIMEN_NUMBER", "Not used here"),
      mandatory_fk_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_GEAR_INTERACTION_CODE", column_location("ros_ll.additional_catch_details_on_ssi", "gear_interaction_code"), column_location("refs_biological.gear_interactions", "code")),
      optional_fk_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_HOOK_TYPE_CODE", column_location("ros_ll.additional_catch_details_on_ssi", "?"), column_location("refs_fishery.hook_types", "code"), "Fixme : not found"),
      optional_fk_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_BAIT_CONDITION_CODE", column_location("ros_ll.additional_catch_details_on_ssi", "bait_condition_code"), column_location("refs_biological.bait_conditions", "code")),
      optional_fk_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_BAIT_TYPE_CODE", column_location("os_ll.additional_catch_details_on_ssi", "bait_type"), column_location("refs_biological.bait_types", "code")),
      mandatory_fk_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_LEADER_MATERIAL_CODE", column_location("ros_ll.additional_catch_details_on_ssi", "leader_material_type_code"), column_location("refs_fishery.line_material_types", "code")),
      optional_measurement_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_LEADER_DIAMETER_MM", column_location("ros_ll.additional_catch_details_on_ssi", "leader_thickness_id"), "ros_common.thicknesses", "MM"),
      optional_fk_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_DE_HOOKER_DEVICE_CODE", column_location("ros_ll.additional_catch_details_on_ssi", "dehooker_device_code"), column_location("refs_fishery.dehooker_types", "code")),
      optional_simple_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_LIGHT_ATTACHED", column_location("ros_ll.additional_catch_details_on_ssi", "light_attached_to_branchline")),
      optional_simple_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_BROUGHT_ONBOARD", column_location("ros_ll.additional_catch_details_on_ssi", "brought_on_board")),
      optional_fk_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_HANDLING_METHOD_CODE", column_location("ros_ll.additional_catch_details_on_ssi", "handling_method_code"), column_location("refs_biological.handling_methods", "code")),
      optional_simple_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_REVIVAL", column_location("ros_ll.additional_catch_details_on_ssi", "revival")),
      optional_simple_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_PHOTO_ID", column_location("ros_ll.additional_catch_details_on_ssi", "photo_id")))),
    sheet("T-EVENTS", "#[19] = T-EVENTS | From row 6 - 15 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Removed in version 3.3.0"),
      ignored_column("TRANSSHIPMENT_NUMBER", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_START_EVENT_DATE_TIME_UTC", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_START_EVENT_LATITUDE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_START_EVENT_LONGITUDE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_END_EVENT_DATE_TIME_UTC", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_END_EVENT_LATITUDE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_END_EVENT_LONGITUDE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_CATEGORY_CODE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_NAME", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_FLAG_OR_CHARTERING_CODE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_IRCS", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_REGISTRATION_COUNTRY_CODE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_REGISTRATION_PORT_CODE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_REGISTRATION_NUMBER", "Removed in version 3.3.0"))),
    sheet("T-PRODUCTS", "#[20] = T-PRODUCTS | From row 6 - 6 columns", c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Removed in version 3.3.0"),
      ignored_column("TRANSSHIPMENT_NUMBER", "Removed in version 3.3.0"),
      ignored_column("PRODUCT_TRANSSHIPPED_SPECIES_CODE", "Removed in version 3.3.0"),
      ignored_column("PRODUCT_TRANSSHIPPED_PROCESSING_TYPE_CODE", "Removed in version 3.3.0"),
      ignored_column("PRODUCT_TRANSSHIPPED_QUANTITY_VALUE", "Removed in version 3.3.0"),
      ignored_column("PRODUCT_TRANSSHIPPED_QUANTITY_KG_T", "Removed in version 3.3.0")))))
