#' The import file model for the ROS_LL_v3_2_1
#' @export
ROS_LL_v3_2_1_MODEL <-
  import_file("ROS_LL_v3_2_1", 
    meta_sheet("META", c(
      mandatory_meta_cell("form_version", 3, 5, expected = "1.0.0"),
      mandatory_meta_cell("data_model_version", 4, 5, expected = "3.2.1"),
      mandatory_meta_cell("liaison_officer_full_name", 9, 5),
      mandatory_meta_cell("liaison_officer_email", 10, 5),
      mandatory_meta_cell("organisation_name", 8, 5),
      mandatory_meta_cell("finalisation_date", 11, 5, format = "[0-9]{4}-[0-9]{2}-[0-9]{2}$"),
      mandatory_meta_cell("submission_date", 12, 5, format = "[0-9]{4}-[0-9]{2}-[0-9]{2}$"),
      mandatory_meta_cell("comments", 14, 3))), c(
    sheet("O-INFO", "#[ 2] = O-INFO | From row 6 - 25 columns", 1, c(
      mandatory_simple_column("OBSERVED_TRIP_NUMBER", column_location("ros_common.general_vessel_and_trip_information→trip_original_id"), actions =  c(new_query(), add_column())),
      mandatory_simple_column("OBSERVER_IDENTIFICATION_OBSERVER_IOTC_NUMBER", column_location("ros_common.observer_identification→iotc_number"), actions =  c(new_query(), add_column(), add_fk_column(column_location("ros_common.general_vessel_and_trip_information→observer_identification_id")))),
      optional_simple_column("OBSERVER_IDENTIFICATION_FULL_NAME", column_location("ros_common.observer_identification→full_name"), actions =  c(add_column())),
      ignored_column("OBSERVER_IDENTIFICATION_NATIONALITY_CODE", "Removed in version 3.3.0"),
      optional_fk_column("OBSERVER_TRIP_DETAILS_EMBARKATION_IN_PORT_COUNTRY_CODE", column_location("ros_common.locations→country_code"), column_location("refs_admin.countries→code"), actions =  c(add_column())),
      optional_fk_column("OBSERVER_TRIP_DETAILS_EMBARKATION_IN_PORT_PORT_CODE", column_location("ros_common.locations→port_code"), column_location("refs_admin.ports→code"), actions =  c(add_column())),
      optional_simple_column("OBSERVER_TRIP_DETAILS_EMBARKATION_AT_SEA_LATITUDE", column_location("ros_common.locations→latitude"), actions =  c(add_column(), flush_query())),
      optional_simple_column("OBSERVER_TRIP_DETAILS_EMBARKATION_AT_SEA_LONGITUDE", column_location("ros_common.locations→longitude"), actions =  c(add_column())),
      optional_simple_column("OBSERVER_TRIP_DETAILS_EMBARKATION_AT_SEA_TIMESTAMP", column_location("ros_common.observer_trip_details→date_time_embarkation"), actions =  c(new_query(), add_fk_column(column_location("ros_common.observer_trip_details→disembarkation_location_id")), add_column())),
      optional_fk_column("OBSERVER_TRIP_DETAILS_DISEMBARKATION_IN_PORT_COUNTRY_CODE", column_location("ros_common.locations→country_code"), column_location("refs_admin.countries→code"), actions =  c(add_column())),
      optional_fk_column("OBSERVER_TRIP_DETAILS_DISEMBARKATION_IN_PORT_PORT_CODE", column_location("ros_common.locations→port_code"), column_location("refs_admin.ports→code"), actions =  c(add_column())),
      optional_simple_column("OBSERVER_TRIP_DETAILS_DISEMBARKATION_AT_SEA_LATITUDE", column_location("ros_common.locations→latitude"), actions =  c(add_column(), flush_query())),
      optional_simple_column("OBSERVER_TRIP_DETAILS_DISEMBARKATION_AT_SEA_LONGITUDE", column_location("ros_common.locations→longitude"), actions =  c(add_column(), flush_query())),
      optional_simple_column("OBSERVER_TRIP_DETAILS_DISEMBARKATION_AT_SEA_TIMESTAMP", column_location("ros_common.observer_trip_details→date_time_disembarkation"), actions =  c(new_query(), add_fk_column(column_location("ros_common.general_vessel_and_trip_information→observed_trip_summary_id")), add_column())),
      mandatory_simple_column("OBSERVED_TRIP_SUMMARY_NUMBER_OF_SETS_CONDUCTED", column_location("ros_common.observed_trip_summary→number_of_conducted_fishing_events_with_observer_onboard"), actions =  c(add_column())),
      mandatory_simple_column("OBSERVED_TRIP_SUMMARY_NUMBER_OF_SETS_OBSERVED", column_location("ros_common.observed_trip_summary→number_of_observed_fishing_events"), actions =  c(add_column())),
      mandatory_simple_column("OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_SEARCHING", column_location("ros_common.observed_trip_summary→number_of_days_searching"), actions =  c(add_column())),
      mandatory_simple_column("OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_ACTIVELY_FISHING", column_location("ros_common.observed_trip_summary→number_of_active_fishing_days"), actions =  c(add_column())),
      optional_simple_column("OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_IN_FISHING_AREA", column_location("ros_common.observed_trip_summary→number_of_days_in_fishing_area"), actions =  c(add_column())),
      optional_simple_column("OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_TRANSITING", column_location("ros_common.observed_trip_summary→number_of_days_transiting"), actions =  c(add_column(), flush_query())),
      mandatory_simple_column("OBSERVED_TRIP_SUMMARY_NUMBER_OF_DAYS_LOST", column_location("ros_common.observed_trip_summary→number_of_days_lost"), actions =  c(new_query(), add_column(), add_fk_column(column_location("ros_common.reasons_for_days_lost→observed_trip_summary_id")), flush_query())),
      optional_fk_column("OBSERVED_TRIP_SUMMARY_REASONS_FOR_DAYS_LOST_REASON_1_CODE", column_location("ros_common.reasons_for_days_lost→inoperativity_reason"), column_location("refs_fishery.reasons_days_lost→code"), actions =  c(new_query(), add_column(), add_fk_column(column_location("ros_common.reasons_for_days_lost→observed_trip_summary_id")), flush_query())),
      optional_fk_column("OBSERVED_TRIP_SUMMARY_REASONS_FOR_DAYS_LOST_REASON_2_CODE", column_location("ros_common.reasons_for_days_lost→inoperativity_reason"), column_location("refs_fishery.reasons_days_lost→code"), actions =  c(new_query(), add_column(), add_fk_column(column_location("ros_common.reasons_for_days_lost→observed_trip_summary_id")), flush_query())),
      optional_fk_column("OBSERVED_TRIP_SUMMARY_REASONS_FOR_DAYS_LOST_REASON_3_CODE", column_location("ros_common.reasons_for_days_lost→inoperativity_reason"), column_location("refs_fishery.reasons_days_lost→code"), actions =  c(new_query(), add_column(), add_fk_column(column_location("ros_common.reasons_for_days_lost→observed_trip_summary_id")), flush_query())),
      optional_fk_column("OBSERVED_TRIP_SUMMARY_REASONS_FOR_DAYS_LOST_REASON_4_CODE", column_location("ros_common.reasons_for_days_lost→inoperativity_reason"), column_location("refs_fishery.reasons_days_lost→code"), actions =  c(new_query(), add_column(), add_fk_column(column_location("ros_common.reasons_for_days_lost→observed_trip_summary_id")), flush_query())))),
    sheet("V-INFO", "#[ 3] = V-INFO | From row 6 - 32 columns", 1, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      mandatory_simple_column("VESSEL_INFORMATION_IDENTIFICATION_NAME", column_location("ros_common.vessel_identification→NAME"), actions =  c(new_query(), add_column(), add_fk_column(column_location("ros_common.general_vessel_and_trip_information→vessel_identification_id")))),
      mandatory_fk_column("VESSEL_INFORMATION_IDENTIFICATION_FLAG_OR_CHARTERING_CODE", column_location("ros_common.vessel_identification→flag_code"), column_location("refs_admin.countries→code"), "Fixme : not found", actions =  c(add_column())),
      mandatory_simple_column("VESSEL_INFORMATION_IDENTIFICATION_IOTC_NUMBER", column_location("ros_common.vessel_identification→iotc_number"), actions =  c(add_column())),
      optional_simple_column("VESSEL_INFORMATION_IDENTIFICATION_IMO_NUMBER", column_location("ros_common.vessel_identification→imo_number"), actions =  c(add_column())),
      optional_simple_column("VESSEL_INFORMATION_IDENTIFICATION_IRCS", column_location("ros_common.vessel_identification→ircs"), actions =  c(add_column())),
      mandatory_fk_column("VESSEL_INFORMATION_IDENTIFICATION_REGISTRATION_COUNTRY_CODE", column_location("ros_common.vessel_identification→flag_code"), column_location("refs_admin.countries→code"), actions =  c(add_column())),
      optional_fk_column("VESSEL_INFORMATION_IDENTIFICATION_REGISTRATION_PORT_CODE", column_location("ros_common.vessel_identification→port_code"), column_location("refs_admin.ports→code"), actions =  c(add_column())),
      optional_simple_column("VESSEL_INFORMATION_IDENTIFICATION_REGISTRATION_NUMBER", column_location("ros_common.vessel_identification→registration_number"), actions =  c(add_column())),
      ignored_column("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_PHONE_1", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_PHONE_2", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_FAX_1", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_FAX_2", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_EMAIL_1", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_IDENTIFICATION_CONTACT_EMAIL_2", "Removed in version 3.3.0"),
      optional_fk_column("VESSEL_INFORMATION_IDENTIFICATION_LICENSED_TARGET_SPECIES_SPECIES_1_CODE", column_location("ros_common.vessel_identification_licensed_target_species→licensed_target_species_code"), column_location("refs_biological.species→code"), actions =  c(new_association_query("ros_common.vessel_identification", column_location("ros_common.vessel_identification_licensed_target_species→vessel_identification_id")), add_fk_column(column_location("ros_common.vessel_identification→vessel_identification_id")), add_column(), flush_query())),
      optional_fk_column("VESSEL_INFORMATION_IDENTIFICATION_LICENSED_TARGET_SPECIES_SPECIES_2_CODE", column_location("ros_common.vessel_identification_licensed_target_species→licensed_target_species_code"), column_location("refs_biological.species→code"), actions =  c(new_association_query("ros_common.vessel_identification", column_location("ros_common.vessel_identification_licensed_target_species→vessel_identification_id")), add_fk_column(column_location("ros_common.vessel_identification→vessel_identification_id")), add_column(), flush_query())),
      optional_fk_column("VESSEL_INFORMATION_IDENTIFICATION_LICENSED_TARGET_SPECIES_SPECIES_3_CODE", column_location("ros_common.vessel_identification_licensed_target_species→licensed_target_species_code"), column_location("refs_biological.species→code"), actions =  c(new_association_query("ros_common.vessel_identification", column_location("ros_common.vessel_identification_licensed_target_species→vessel_identification_id")), add_fk_column(column_location("ros_common.vessel_identification→vessel_identification_id")), add_column(), flush_query())),
      optional_fk_column("VESSEL_INFORMATION_IDENTIFICATION_LICENSED_TARGET_SPECIES_SPECIES_4_CODE", column_location("ros_common.vessel_identification_licensed_target_species→licensed_target_species_code"), column_location("refs_biological.species→code"), actions =  c(new_association_query("ros_common.vessel_identification", column_location("ros_common.vessel_identification_licensed_target_species→vessel_identification_id")), add_fk_column(column_location("ros_common.vessel_identification→vessel_identification_id")), add_column(), flush_query())),
      mandatory_fk_column("VESSEL_INFORMATION_IDENTIFICATION_MAIN_FISHING_GEAR_CODE", column_location("ros_common.vessel_identification→main_fishing_gear_code"), column_location("refs_fishery_config.gears→code"), actions =  c(add_column(), flush_query())),
      ignored_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_OWNER_FULL_NAME", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_OWNER_NATIONALITY_CODE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_OWNER_CONTACT_DETAILS", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CHARTER_OR_OPERATOR_FULL_NAME", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CHARTER_OR_OPERATOR_NATIONALITY_CODE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CHARTER_OR_OPERATOR_CONTACT_DETAILS", "Removed in version 3.3.0"),
      ignored_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CHARTER_OR_OPERATOR_CONTACT_DETAILS2", "Removed in version 3.3.0"),
      mandatory_simple_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_FISHING_MASTER_FULL_NAME", column_location("ros_common.person_details→full_name"), actions =  c(new_query(), add_fk_column(column_location("ros_common.vessel_owner_and_personnel→fishing_master_id")), add_column())),
      mandatory_fk_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_FISHING_MASTER_NATIONALITY_CODE", column_location("ros_common.person_details→nationality_code"), column_location("refs_admin.countries→code"), actions =  c(add_column(), flush_query())),
      mandatory_simple_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_SKIPPER_CAPTAIN_FULL_NAME", column_location("ros_common.person_details→full_name"), actions =  c(new_query(), add_fk_column(column_location("ros_common.vessel_owner_and_personnel→skipper_id")), add_column())),
      mandatory_fk_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_SKIPPER_CAPTAIN_NATIONALITY_CODE", column_location("ros_common.person_details→nationality_code"), column_location("refs_admin.countries→code"), actions =  c(add_column(), flush_query())),
      optional_simple_column("VESSEL_INFORMATION_OWNER_AND_PERSONNEL_CREW_NUMBER", column_location("ros_common.vessel_owner_and_personnel→number_of_crew"), actions =  c(add_column(), flush_query())))),
    sheet("V-TRIP", "#[ 4] = V-TRIP | From row 6 - 11 columns", 1, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("TRIP_DETAILS_VESSEL_DEPARTURE_PORT_COUNTRY_CODE", "Removed in version 3.3.0"),
      optional_fk_column("TRIP_DETAILS_VESSEL_DEPARTURE_PORT_PORT_CODE", column_location("ros_common.vessel_trip_details→departure_port_code"), column_location("refs_admin.ports→code"), actions =  c(new_query(), add_column(), add_fk_column(column_location("ros_common.general_vessel_and_trip_information→vessel_trip_details_id")))),
      ignored_column("TRIP_DETAILS_VESSEL_DEPARTURE_PORT_LATITUDE", "Removed in version 3.3.0"),
      ignored_column("TRIP_DETAILS_VESSEL_DEPARTURE_PORT_LONGITUDE", "Removed in version 3.3.0"),
      optional_simple_column("TRIP_DETAILS_VESSEL_DEPARTURE_TIMESTAMP", column_location("ros_common.vessel_trip_details→date_time_vessel_sailed"), actions =  c(add_column())),
      ignored_column("TRIP_DETAILS_VESSEL_RETURN_PORT_COUNTRY_CODE", "Removed in version 3.3.0"),
      optional_fk_column("TRIP_DETAILS_VESSEL_RETURN_PORT_PORT_CODE", column_location("ros_common.vessel_trip_details→return_port_code"), column_location("refs_admin.ports→code"), actions =  c(add_column())),
      ignored_column("TRIP_DETAILS_VESSEL_RETURN_PORT_LATITUDE", "Removed in version 3.3.0"),
      ignored_column("TRIP_DETAILS_VESSEL_RETURN_PORT_LONGITUDE", "Removed in version 3.3.0"),
      optional_simple_column("TRIP_DETAILS_VESSEL_RETURN_TIMESTAMP", column_location("ros_common.vessel_trip_details→date_time_vessel_returned_to_port"), actions =  c(add_column(), flush_query())))),
    sheet("V-ATTRIBUTES", "#[ 5] = V-ATTRIBUTES | From row 6 - 50 columns", 1, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      mandatory_measurement_column("VESSEL_ATTRIBUTES_TONNAGE_VALUE", column_location("ros_common.vessel_attributes→tonnage_id"), "ros_common.tonnages", actions =  c(new_query(), add_external_fk_column("ros_common.vessel_attributes", column_location("ros_common.general_vessel_and_trip_information→vessel_attributes_id")), new_measurement_query(), add_column())),
      mandatory_measurement_unit_column("VESSEL_ATTRIBUTES_TONNAGE_GT_GRT", c("GT", "GRT"), actions =  c(add_column(), flush_measurement_query())),
      mandatory_measurement_column("VESSEL_ATTRIBUTES_LENGTH_OVERALL_VALUE", column_location("ros_common.vessel_attributes→loa_id"), "ros_common.lengths", actions =  c(new_measurement_query(), add_fk_column(column_location("ros_common.vessel_attributes→loa_id")), add_column())),
      mandatory_measurement_unit_column("VESSEL_ATTRIBUTES_LENGTH_OVERALL_M_FT", c("M", "FT"), actions =  c(flush_measurement_query())),
      mandatory_fk_column("VESSEL_ATTRIBUTES_HULL_MATERIAL_CODE", column_location("ros_common.vessel_attributes→hull_material_code"), column_location("refs_fishery.hull_material_types→code"), actions =  c(add_column(), flush_query())),
      mandatory_simple_column("VESSEL_ATTRIBUTES_MAIN_ENGINE_1_MAKE", column_location("ros_common.engines→make"), actions =  c(new_query(), new_association_query("ros_common.vessel_attributes", column_location("ros_common.vessel_attributes_main_engines→vessel_attributes_id_me")), add_external_fk_column("ros_common.vessel_attributes", column_location("ros_common.vessel_attributes_main_engines→vessel_attributes_id_me")), add_fk_column(column_location("ros_common.vessel_attributes_main_engines→main_engine_id")), add_column())),
      mandatory_measurement_column("VESSEL_ATTRIBUTES_MAIN_ENGINE_1_POWER_VALUE", column_location("ros_common.vessel_attributes_main_engines→main_engine_id"), "ros_common.engines", actions =  c(new_measurement_query(), add_column())),
      mandatory_measurement_unit_column("VESSEL_ATTRIBUTES_MAIN_ENGINE_1_KW_HP_BHP", c("KW", "HP", "BHP"), actions =  c(flush_measurement_query())),
      optional_simple_column("VESSEL_ATTRIBUTES_MAIN_ENGINE_2_MAKE", column_location("ros_common.engines→make"), actions =  c(add_column())),
      optional_measurement_column("VESSEL_ATTRIBUTES_MAIN_ENGINE_2_POWER_VALUE", column_location("ros_common.vessel_attributes_main_engines→main_engine_id"), "ros_common.engines", actions =  c(new_measurement_query(), add_column())),
      optional_measurement_unit_column("VESSEL_ATTRIBUTES_MAIN_ENGINE_2_KW_HP_BHP", c("KW", "HP", "BHP"), actions =  c(flush_measurement_query())),
      mandatory_measurement_column("VESSEL_ATTRIBUTES_FISH_STORAGE_CAPACITY_VALUE", column_location("ros_common.vessel_attributes→fish_storage_capacity_id"), "ros_common.capacities", actions =  c(new_measurement_query(), add_column())),
      optional_measurement_unit_column("VESSEL_ATTRIBUTES_FISH_STORAGE_CAPACITY_T_M3", c("T", "M3"), actions =  c(flush_measurement_query())),
      optional_fk_column("VESSEL_ATTRIBUTES_FISH_PRESERVATION_METHODS_METHOD_1_CODE", column_location("ros_common.vessel_attributes_fish_preservation_method→fish_preservation_method_code"), column_location("refs_fishery.fish_preservation_methods→code"), actions =  c(add_column())),
      optional_fk_column("VESSEL_ATTRIBUTES_FISH_PRESERVATION_METHODS_METHOD_2_CODE", column_location("ros_common.vessel_attributes_fish_preservation_method→fish_preservation_method_code"), column_location("refs_fishery.fish_preservation_methods→code"), actions =  c(add_column())),
      optional_fk_column("VESSEL_ATTRIBUTES_FISH_PRESERVATION_METHODS_METHOD_3_CODE", column_location("ros_common.vessel_attributes_fish_preservation_method→fish_preservation_method_code"), column_location("refs_fishery.fish_preservation_methods→code"), actions =  c(add_column())),
      optional_fk_column("VESSEL_ATTRIBUTES_FISH_PRESERVATION_METHODS_METHOD_4_CODE", column_location("ros_common.vessel_attributes_fish_preservation_method→fish_preservation_method_code"), column_location("refs_fishery.fish_preservation_methods→code"), actions =  c(add_column())),
      optional_fk_column("VESSEL_ATTRIBUTES_FISH_STORAGE_TYPES_TYPE_1_CODE", column_location("ros_common.vessel_attributes_fish_storage_type→fish_storage_type_code"), column_location("refs_fishery.fish_storage_types→code"), actions =  c(add_column())),
      optional_fk_column("VESSEL_ATTRIBUTES_FISH_STORAGE_TYPES_TYPE_2_CODE", column_location("ros_common.vessel_attributes_fish_storage_type→fish_storage_type_code"), column_location("refs_fishery.fish_storage_types→code"), actions =  c(add_column())),
      optional_fk_column("VESSEL_ATTRIBUTES_FISH_STORAGE_TYPES_TYPE_3_CODE", column_location("ros_common.vessel_attributes_fish_storage_type→fish_storage_type_code"), column_location("refs_fishery.fish_storage_types→code"), actions =  c(add_column())),
      optional_measurement_column("VESSEL_ATTRIBUTES_AUTONOMY_RANGE_VALUE", column_location("ros_common.vessel_attributes→autonomy_range_id"), "ros_common.ranges", actions =  c(new_measurement_query(), add_column())),
      optional_measurement_unit_column("VESSEL_ATTRIBUTES_AUTONOMY_RANGE_DAYS_NM", c("DAYS", "NM"), actions =  c(flush_measurement_query())),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_GPS", column_location("ros_common.vessel_electronics→gps"), actions =  c(add_column())),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_VMS", column_location("ros_common.vessel_electronics→vms"), actions =  c(add_column())),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_AIS", column_location("ros_common.vessel_electronics→ais"), actions =  c(add_column())),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_RADARS", column_location("ros_common.vessel_electronics→radars"), actions =  c(add_column())),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_TRACK_PLOTTER", column_location("ros_common.vessel_electronics→track_plotter"), actions =  c(add_column())),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_DEPTH_SOUNDER", column_location("ros_common.vessel_electronics→depth_sounder"), actions =  c(add_column())),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_SONAR", column_location("ros_common.vessel_electronics→sonar"), actions =  c(add_column())),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_DOPPLER_CURRENT_METER", column_location("ros_common.vessel_electronics→doppler_current_meter"), actions =  c(add_column())),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_XBT", column_location("ros_common.vessel_electronics→expendable_bathythermographs"), actions =  c(add_column())),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_VHF_RADIOS", column_location("ros_common.vessel_electronics→vhf_radios"), actions =  c(add_column())),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_HF_RADIOS", column_location("ros_common.vessel_electronics→hf_radios"), actions =  c(add_column())),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_SATELLITE_COMM", column_location("ros_common.vessel_electronics→satellite_communication_systems"), actions =  c(add_column())),
      ignored_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_SST_GAUGE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_WEATHER_FAX", "Removed in version 3.3.0"),
      optional_simple_column("VESSEL_ATTRIBUTES_VESSEL_ELECTRONICS_FIS", column_location("ros_common.vessel_electronics→fisheries_information_services"), actions =  c(add_column())),
      mandatory_fk_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_1_CATEGORY_1_CODE", column_location("ros_common.waste_managements→waste_category_code"), column_location("refs_fishery.waste_categories→code"), actions =  c(add_column())),
      mandatory_fk_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_1_STORAGE_DISPOSAL_METHOD_1_CODE", column_location("ros_common.waste_managements→waste_storage_or_disposal_method_code"), column_location("refs_fishery.waste_disposal_methods→code"), actions =  c(add_column())),
      ignored_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_1_OTHER_1", "Removed in version 3.3.0"),
      optional_fk_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_2_CATEGORY_2_CODE", column_location("ros_common.waste_managements→waste_category_code"), column_location("refs_fishery.waste_categories→code"), actions =  c(add_column())),
      optional_fk_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_2_STORAGE_DISPOSAL_METHOD_2_CODE", column_location("ros_common.waste_managements→waste_storage_or_disposal_method_code"), column_location("refs_fishery.waste_disposal_methods→code"), actions =  c(add_column())),
      ignored_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_2_OTHER_2", "Removed in version 3.3.0"),
      optional_fk_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_3_CATEGORY_3_CODE", column_location("ros_common.waste_managements→waste_category_code"), column_location("refs_fishery.waste_categories→code"), actions =  c(add_column())),
      optional_fk_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_3_STORAGE_DISPOSAL_METHOD_3_CODE", column_location("ros_common.waste_managements→waste_storage_or_disposal_method_code"), column_location("refs_fishery.waste_disposal_methods→code"), actions =  c(add_column())),
      ignored_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_3_OTHER_3", "Removed in version 3.3.0"),
      optional_fk_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_4_CATEGORY_4_CODE", column_location("ros_common.waste_managements→waste_category_code"), column_location("refs_fishery.waste_categories→code"), actions =  c(add_column())),
      optional_fk_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_4_STORAGE_DISPOSAL_METHOD_4_CODE", column_location("ros_common.waste_managements→waste_storage_or_disposal_method_code"), column_location("refs_fishery.waste_disposal_methods→code"), actions =  c(add_column())),
      ignored_column("VESSEL_ATTRIBUTES_WASTE_MANAGEMENT_WASTE_MANAGEMENT_DETAIL_4_OTHER_4", "Removed in version 3.3.0"))),
    sheet("G-GENERAL", "#[ 6] = G-GENERAL | From row 6 - 33 columns", 1, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      mandatory_simple_column("SPECIAL_EQUIPMENT_OR_MACHINERY_LINE_SETTER", column_location("ros_ll.special_equipment→line_setter"), actions =  c(add_column())),
      mandatory_simple_column("SPECIAL_EQUIPMENT_OR_MACHINERY_LINE_HAULER", column_location("ros_ll.special_equipment→line_hauler"), actions =  c(add_column())),
      mandatory_simple_column("SPECIAL_EQUIPMENT_OR_MACHINERY_BAIT_CASTING_MACHINE", column_location("ros_ll.special_equipment→bait_casting_machine"), actions =  c(add_column())),
      ignored_column("GENERAL_GEAR_ATTRIBUTES_MAINLINE_MATERIAL_CODE", "Removed in version 3.3.0"),
      ignored_column("GENERAL_GEAR_ATTRIBUTES_MAINLINE_LENGTH_VALUE", "Removed in version 3.3.0"),
      ignored_column("GENERAL_GEAR_ATTRIBUTES_MAINLINE_LENGTH_KM_NM", "Removed in version 3.3.0"),
      ignored_column("GENERAL_GEAR_ATTRIBUTES_MAINLINE_DIAMETER_VALUE", "Removed in version 3.3.0"),
      ignored_column("GENERAL_GEAR_ATTRIBUTES_MAINLINE_DIAMETER_MM_CM", "Removed in version 3.3.0"),
      optional_fk_column("ADDITIONAL_BRANCHLINE_DETAILS_STORAGE_1_CODE", column_location("ros_ll.branchline_configurations_storage→branchline_storage_code"), column_location("refs_fishery.branchline_storages→code"), "Added in version 3.3.0", actions =  c(new_query("ros_ll.branchline_configurations"), new_association_query("ros_ll.branchline_configurations", column_location("ros_ll.branchline_configurations_storage→branchline_storage_code")), add_column(), add_external_fk_column("ros_ll.branchline_configurations", column_location("ros_ll.branchline_configurations_storage→branchline_configuration_id")), flush_query())),
      optional_fk_column("ADDITIONAL_BRANCHLINE_DETAILS_STORAGE_2_CODE", column_location("ros_ll.branchline_configurations_storage→branchline_storage_code"), column_location("refs_fishery.branchline_storages→code"), "Added in version 3.3.0", actions =  c(new_query("ros_ll.branchline_configurations"), new_association_query("ros_ll.branchline_configurations", column_location("ros_ll.branchline_configurations_storage→branchline_storage_code")), add_column(), add_external_fk_column("ros_ll.branchline_configurations", column_location("ros_ll.branchline_configurations_storage→branchline_configuration_id")), flush_query())),
      optional_fk_column("ADDITIONAL_BRANCHLINE_DETAILS_STORAGE_3_CODE", column_location("ros_ll.branchline_configurations_storage→branchline_storage_code"), column_location("refs_fishery.branchline_storages→code"), "Added in version 3.3.0", actions =  c(new_query("ros_ll.branchline_configurations"), new_association_query("ros_ll.branchline_configurations", column_location("ros_ll.branchline_configurations_storage→branchline_storage_code")), add_column(), add_external_fk_column("ros_ll.branchline_configurations", column_location("ros_ll.branchline_configurations_storage→branchline_configuration_id")), flush_query())),
      optional_fk_column("ADDITIONAL_BRANCHLINE_DETAILS_STORAGE_4_CODE", column_location("ros_ll.branchline_configurations_storage→branchline_storage_code"), column_location("refs_fishery.branchline_storages→code"), "Added in version 3.3.0", actions =  c(new_query("ros_ll.branchline_configurations"), new_association_query("ros_ll.branchline_configurations", column_location("ros_ll.branchline_configurations_storage→branchline_storage_code")), add_column(), add_external_fk_column("ros_ll.branchline_configurations", column_location("ros_ll.branchline_configurations_storage→branchline_configuration_id")), flush_query())),
      optional_fk_column("MITIGATION_DEVICES_DEVICE_1_CODE", column_location("ros_ll.gear_specifications_mitigation_device→mitigation_device_code"), column_location("refs_fishery.mitigation_devices→code"), actions =  c(add_column())),
      optional_fk_column("MITIGATION_DEVICES_DEVICE_2_CODE", column_location("ros_ll.gear_specifications_mitigation_device→mitigation_device_code"), column_location("refs_fishery.mitigation_devices→code"), actions =  c(add_column())),
      optional_fk_column("MITIGATION_DEVICES_DEVICE_3_CODE", column_location("ros_ll.gear_specifications_mitigation_device→mitigation_device_code"), column_location("refs_fishery.mitigation_devices→code"), actions =  c(add_column())),
      optional_fk_column("MITIGATION_DEVICES_DEVICE_4_CODE", column_location("ros_ll.gear_specifications_mitigation_device→mitigation_device_code"), column_location("refs_fishery.mitigation_devices→code"), actions =  c(add_column())),
      optional_fk_column("MITIGATION_DEVICES_DEVICE_5_CODE", column_location("ros_ll.gear_specifications_mitigation_device→mitigation_device_code"), column_location("refs_fishery.mitigation_devices→code"), actions =  c(add_column())),
      optional_measurement_column("TORI_LINE_DETAILS_TORI_LINE_LENGTH_VALUE", column_location("ros_ll.tori_line_details→tori_line_length_id"), "ros_common.lengths", actions =  c(new_measurement_query(), add_column())),
      optional_measurement_unit_column("TORI_LINE_DETAILS_TORI_LINE_LENGTH_M_FT", c("M", "FT"), actions =  c(flush_measurement_query())),
      optional_fk_column("TORI_LINE_DETAILS_STREAMER_TYPE_CODE", column_location("ros_ll.tori_line_details→streamer_type"), column_location("refs_fishery.streamer_types→code"), actions =  c(add_column())),
      optional_simple_column("TORI_LINE_DETAILS_STREAMER_REACH_SURFACE", column_location("ros_ll.tori_line_details→streamers_reach_surface"), actions =  c(add_column())),
      optional_measurement_column("TORI_LINE_DETAILS_STREAMER_LINE_LENGTH_MAX_VALUE", column_location("ros_ll.tori_line_details→streamer_line_length_max_id"), "ros_common.lengths", actions =  c(new_measurement_query(), add_column())),
      optional_measurement_unit_column("TORI_LINE_DETAILS_STREAMER_LINE_LENGTH_MAX_CM_M_FT", c("CM", "M", "FT"), actions =  c(flush_measurement_query())),
      optional_measurement_column("TORI_LINE_DETAILS_STREAMER_LINE_LENGTH_MIN_VALUE", column_location("ros_ll.tori_line_details→streamer_line_length_min_id"), "ros_common.lengths", actions =  c(new_measurement_query(), add_column())),
      optional_measurement_unit_column("TORI_LINE_DETAILS_STREAMER_LINE_LENGTH_MIN_CM_M_FT", c("CM", "M", "FT"), actions =  c(flush_measurement_query())),
      optional_simple_column("TORI_LINE_DETAILS_STREAMER_NUMBER_PER_LINE", column_location("ros_ll.tori_line_details→number_of_streamers_per_line"), actions =  c(add_column())),
      optional_measurement_column("TORI_LINE_DETAILS_DISTANCE_BETWEEN_STREAMERS_VALUE", column_location("ros_ll.tori_line_details→streamer_distance_id"), "ros_common.distances", actions =  c(new_measurement_query(), add_column())),
      optional_measurement_unit_column("TORI_LINE_DETAILS_DISTANCE_BETWEEN_STREAMERS_CM_M_FT", c("CM", "M", "FT"), actions =  c(flush_measurement_query())),
      optional_measurement_column("TORI_LINE_DETAILS_TORI_LINE_ATTACHED_HEIGHT_VALUE", column_location("ros_ll.tori_line_details→attached_height_id"), "ros_common.heights", actions =  c(new_measurement_query(), add_column())),
      optional_measurement_unit_column("TORI_LINE_DETAILS_TORI_LINE_ATTACHED_HEIGHT_CM_M_FT", c("CM", "M", "FT"), actions =  c(flush_measurement_query())),
      optional_simple_column("TORI_LINE_DETAILS_TOWED_OBJECTS_NUMBER", column_location("ros_ll.tori_line_details→towed_objects_number"), actions =  c(add_column())),
      optional_simple_column("TORI_LINE_DETAILS_TOWED_OBJECTS_TYPE", column_location("ros_ll.tori_line_details→towed_objects_type"), actions =  c(add_column())))),
    sheet("G-CONFIG-BRANCHLINES", "#[ 7] = G-CONFIG-BRANCHLINES | From row 6 - 8 columns", 1, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      mandatory_simple_column("BRANCHLINE_CONFIGURATIONS_CONFIGURATION_NUMBER", column_location("ros_ll.branchline_configurations→configuration_original_id"), actions =  c(add_column(), add_external_fk_column("ros_ll.gear_specifications", column_location("ros_ll.branchline_configurations→gear_specifications_id")), flush_query())),
      mandatory_simple_column("BRANCHLINE_CONFIGURATIONS_SECTION_NUMBER", column_location("ros_ll.branchline_sections→section_number"), actions =  c(new_query(), add_column(), add_external_fk_column("ros_ll.branchline_configurations", column_location("ros_ll.branchline_sections→branchline_configuration_id")))),
      optional_fk_column("BRANCHLINE_CONFIGURATIONS_MATERIAL_TYPE_CODE", column_location("ros_ll.branchline_sections→branchline_material_type_code"), column_location("refs_fishery.line_material_types→code"), actions =  c(add_column())),
      mandatory_measurement_column("BRANCHLINE_CONFIGURATIONS_LENGTH_VALUE", column_location("ros_ll.branchline_sections→length_id"), "ros_common.lengths", actions =  c(new_measurement_query(), add_column())),
      mandatory_measurement_unit_column("BRANCHLINE_CONFIGURATIONS_LENGTH_CM_M", c("CM", "M"), actions =  c(add_column(), flush_measurement_query())),
      mandatory_measurement_column("BRANCHLINE_CONFIGURATIONS_DIAMETER_VALUE", column_location("ros_ll.branchline_sections→diameter_id"), "ros_common.diameters", actions =  c(new_measurement_query(), add_column())),
      mandatory_measurement_unit_column("BRANCHLINE_CONFIGURATIONS_DIAMETER_MM_CM", c("MM", "CM"), actions =  c()))),
    sheet("E-SET", "#[ 8] = E-SET | From row 6 - 24 columns", 2, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      mandatory_simple_column("SET_NUMBER", column_location("ros_ll.fishing_events→event_original_id"), actions =  c(new_query(), add_column(), add_fk_column(column_location("ros_ll.observer_data→observer_data_id")))),
      mandatory_simple_column("SETTING_OPERATIONS_START_SETTING_DATE_TIME_UTC", column_location("ros_ll.setting_operations→start_setting_date_and_time"), actions =  c(add_column(), add_fk_column(column_location("ros_ll.fishing_events→setting_operation_id")))),
      mandatory_simple_column("SETTING_OPERATIONS_START_SETTING_LATITUDE", column_location("ros_ll.setting_operations→start_setting_latitude"), actions =  c(add_column())),
      mandatory_simple_column("SETTING_OPERATIONS_START_SETTING_LONGITUDE", column_location("ros_ll.setting_operations→start_setting_longitude"), actions =  c(add_column())),
      mandatory_simple_column("SETTING_OPERATIONS_END_SETTING_DATE_TIME_UTC", column_location("ros_ll.setting_operations→end_setting_date_and_time"), actions =  c(add_column())),
      mandatory_simple_column("SETTING_OPERATIONS_END_SETTING_LATITUDE", column_location("ros_ll.setting_operations→end_setting_latitude"), actions =  c(add_column())),
      mandatory_simple_column("SETTING_OPERATIONS_END_SETTING_LONGITUDE", column_location("ros_ll.setting_operations→end_setting_longitude"), actions =  c(add_column())),
      mandatory_simple_column("SETTING_OPERATIONS_SPEED_VESSEL_VALUE_KNOTS", column_location("ros_ll.setting_operations→vessel_speed"), actions =  c(add_column())),
      mandatory_simple_column("SETTING_OPERATIONS_SPEED_LINE_SETTER_VALUE_MS", column_location("ros_ll.setting_operations→line_setter_speed"), actions =  c(add_column())),
      mandatory_measurement_column("SETTING_OPERATIONS_MAINLINE_LENGTH_VALUE", column_location("ros_ll.setting_operations→mainline_set_length_id"), "ros_common.lengths", actions =  c(new_measurement_query(), add_column())),
      mandatory_measurement_unit_column("SETTING_OPERATIONS_MAINLINE_LENGTH_KM_NM", c("KM", "NM"), actions =  c(flush_measurement_query())),
      optional_simple_column("SETTING_OPERATIONS_CLIP_ON_TIME_BRANCHLINE", column_location("ros_ll.setting_operations→branchline_clip_on_time"), actions =  c(add_column())),
      optional_simple_column("SETTING_OPERATIONS_CLIP_ON_TIME_BUOYS", column_location("ros_ll.setting_operations→buoys_clip_on_time"), actions =  c(add_column())),
      mandatory_simple_column("SETTING_OPERATIONS_NUM_TOTAL_HOOKS_SET", column_location("ros_ll.setting_operations→total_number_of_hooks_set"), actions =  c(add_column())),
      optional_simple_column("SETTING_OPERATIONS_NUM_TOTAL_FLOATS_SET", column_location("ros_ll.setting_operations→total_number_of_floats_set"), actions =  c(add_column())),
      mandatory_simple_column("SETTING_OPERATIONS_NUM_HOOKS_BETWEEN_FLOATS", column_location("ros_ll.setting_operations→number_of_hooks_set_between_floats"), actions =  c(add_column())),
      mandatory_simple_column("SETTING_OPERATIONS_SHARK_LINES_SET", column_location("ros_ll.setting_operations→shark_lines_set"), actions =  c(add_column())),
      optional_simple_column("SETTING_OPERATIONS_SHARK_LINES_NUM_LINES", column_location("ros_ll.setting_operations→number_of_shark_lines_set"), actions =  c(add_column())),
      mandatory_fk_column("SETTING_OPERATIONS_TARGET_SPECIES_SPECIES_1_CODE", column_location("ros_ll.setting_operations_target_species→target_species_code"), column_location("refs_biological.species→code"), actions =  c(new_association_query("ros_ll.setting_operations", column_location("ros_ll.setting_operations_target_species→setting_operations_id")), add_column(), add_external_fk_column("ros_ll.setting_operations", column_location("ros_ll.setting_operations_target_species→setting_operations_id")), flush_query())),
      optional_fk_column("SETTING_OPERATIONS_TARGET_SPECIES_SPECIES_2_CODE", column_location("ros_ll.setting_operations_target_species→target_species_code"), column_location("refs_biological.species→code"), actions =  c(new_association_query("ros_ll.setting_operations", column_location("ros_ll.setting_operations_target_species→setting_operations_id")), add_column(), add_external_fk_column("ros_ll.setting_operations", column_location("ros_ll.setting_operations_target_species→setting_operations_id")), flush_query())),
      optional_fk_column("SETTING_OPERATIONS_TARGET_SPECIES_SPECIES_3_CODE", column_location("ros_ll.setting_operations_target_species→target_species_code"), column_location("refs_biological.species→code"), actions =  c(new_association_query("ros_ll.setting_operations", column_location("ros_ll.setting_operations_target_species→setting_operations_id")), add_column(), add_external_fk_column("ros_ll.setting_operations", column_location("ros_ll.setting_operations_target_species→setting_operations_id")), flush_query())),
      optional_fk_column("SETTING_OPERATIONS_TARGET_SPECIES_SPECIES_4_CODE", column_location("ros_ll.setting_operations_target_species→target_species_code"), column_location("refs_biological.species→code"), actions =  c(new_association_query("ros_ll.setting_operations", column_location("ros_ll.setting_operations_target_species→setting_operations_id")), add_column(), add_external_fk_column("ros_ll.setting_operations", column_location("ros_ll.setting_operations_target_species→setting_operations_id")), flush_query())),
      ignored_column("SETTING_OPERATIONS_VMS_ON", "Removed in version 3.3.0"))),
    sheet("E-SET-LIGHTS", "#[ 9] = E-SET-LIGHTS | From row 6 - 5 columns", 2, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      optional_fk_column("SETTING_OPERATIONS_ATTACHED_LIGHTS_TYPE_CODE", column_location("ros_ll.lights_by_type_and_colour→light_type_code"), column_location("refs_fishery.light_types→code"), actions =  c(new_query(), add_column(), add_external_fk_column("ros_ll.setting_operations", column_location("ros_ll.lights_by_type_and_colour→setting_operations_id")))),
      optional_fk_column("SETTING_OPERATIONS_ATTACHED_LIGHTS_COLOR_CODE", column_location("ros_ll.lights_by_type_and_colour→light_colour_code"), column_location("refs_fishery.light_colours→code"), actions =  c(add_column())),
      optional_simple_column("SETTING_OPERATIONS_ATTACHED_LIGHTS_NUM_LIGHTS", column_location("ros_ll.lights_by_type_and_colour→number_of_lights_by_type_and_colour"), actions =  c(add_column(), flush_query())))),
    sheet("E-SET-BRANCHLINES", "#[ 10] = E-SET-BRANCHLINES | From row 6 - 4 columns", 2, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      optional_simple_column("SETTING_OPERATIONS_BRANCHLINE_DETAILS_CONFIGURATION_NUMBER", column_location("ros_ll.branchlines_set→branchline_configuration_original_id"), actions =  c(new_query(), add_column(), add_external_fk_column("ros_ll.setting_operations", column_location("ros_ll.branchlines_set→setting_operations_id")))),
      optional_simple_column("SETTING_OPERATIONS_BRANCHLINE_DETAILS_NUM_BRANCHLINES_SET", column_location("ros_ll.branchlines_set→number_of_branchlines"), actions =  c(add_column(), flush_query())))),
    sheet("E-SET-HOOKS", "#[ 11] = E-SET-HOOKS | From row 6 - 5 columns", 2, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      mandatory_fk_column("SETTING_OPERATIONS_HOOKS_DETAILS_TYPE_CODE", column_location("ros_ll.hooks_by_type→hook_type_code"), column_location("refs_fishery.hook_types→code"), actions =  c(new_query(), add_column(), add_external_fk_column("ros_ll.setting_operations", column_location("ros_ll.hooks_by_type→setting_operations_id")))),
      optional_simple_column("SETTING_OPERATIONS_HOOKS_DETAILS_PERCENTAGE", column_location("ros_ll.hooks_by_type→percentage_of_set"), actions =  c(add_column())),
      optional_simple_column("SETTING_OPERATIONS_HOOKS_DETAILS_VARIATIONS", column_location("ros_ll.hooks_by_type→variations"), actions =  c(add_column(), flush_query())))),
    sheet("E-SET-BAITS", "#[ 12] = E-SET-BAITS | From row 6 - 6 columns", 2, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      mandatory_fk_column("SETTING_OPERATIONS_BAITS_DETAILS_BAIT_CONDITION_CODE", column_location("ros_ll.baits_by_conditions→bait_condition_code"), column_location("refs_biological.bait_conditions→code"), actions =  c(new_query(), add_external_fk_column("ros_ll.setting_operations", column_location("ros_ll.baits_by_conditions→setting_operations_id")), add_column())),
      mandatory_fk_column("SETTING_OPERATIONS_BAITS_DETAILS_BAIT_SPECIES_CODE", column_location("ros_ll.baits_by_conditions→species_code"), column_location("refs_biological.species→code"), actions =  c(add_column())),
      mandatory_simple_column("SETTING_OPERATIONS_BAITS_DETAILS_BAIT_PERCENTAGE", column_location("ros_ll.baits_by_conditions→ratio"), actions =  c(add_column())),
      optional_simple_column("SETTING_OPERATIONS_BAITS_DETAILS_BAIT_DYE_COLOUR", column_location("ros_ll.baits_by_conditions→dye_colour"), actions =  c(add_column(), flush_query())))),
    sheet("E-SET-MITIGATION-MEASURES", "#[13] = E-SET-MITIGATION-MEASURES | From row 6 - 14 columns", 2, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      mandatory_simple_column("SETTING_OPERATIONS_MITIGATION_MEASURES_NUM_TORI_LINES_DEPLOYED", column_location("ros_ll.mitigation_measures→number_of_tori_lines_deployed"), actions =  c(new_query(), add_column(), add_fk_column(column_location("ros_ll.fishing_events→mitigation_measure_id")))),
      mandatory_simple_column("SETTING_OPERATIONS_MITIGATION_MEASURES_MIN_DECK_LIGHTING_USED", column_location("ros_ll.mitigation_measures→minimum_deck_lighting_used"), actions =  c(add_column())),
      mandatory_simple_column("SETTING_OPERATIONS_MITIGATION_MEASURES_HOOKS_SET_BETWEEN_DUSK_DAWN", column_location("ros_ll.mitigation_measures→hooks_set_between_dusk_and_dawn"), actions =  c(add_column())),
      optional_simple_column("SETTING_OPERATIONS_MITIGATION_MEASURES_BRANCHLINE_WEIGHTED", column_location("ros_ll.mitigation_measures→branchline_weighted"), actions =  c(add_column())),
      mandatory_measurement_column("SETTING_OPERATIONS_MITIGATION_MEASURES_AVG_BRANCHLINE_WEIGHT_G", column_location("ros_ll.mitigation_measures→average_sinker_weight_id"), "ros_common.weights", "G", actions =  c(new_measurement_query(), add_column(), flush_measurement_query())),
      mandatory_simple_column("SETTING_OPERATIONS_MITIGATION_MEASURES_PERC_BRANCHLINE_WEIGHTED", column_location("ros_ll.mitigation_measures→percentage_of_branchlines_weighted"), actions =  c(add_column())),
      mandatory_measurement_column("SETTING_OPERATIONS_MITIGATION_MEASURES_HOOK_SINKER_DISTANCE_CM", column_location("ros_ll.mitigation_measures→hook_sinker_distance_id"), "ros_common.distances", "CM", actions =  c(new_measurement_query(), add_column(), flush_measurement_query())),
      mandatory_simple_column("SETTING_OPERATIONS_MITIGATION_MEASURES_UNDERWATER_SETTING", column_location("ros_ll.mitigation_measures→hooks_pods"), actions =  c(add_column(), flush_query())),
      mandatory_fk_column("SETTING_OPERATIONS_MITIGATION_MEASURES_OTHER_MITIGATION_MEASURES_USED_MEASURE_1_CODE", column_location("ros_ll.mitigation_measures_mitigation_devices→mitigation_device_code"), column_location("refs_fishery.mitigation_devices→code"), actions =  c(new_association_query("ros_ll.mitigation_measures", column_location("ros_ll.mitigation_measures_mitigation_devices→mitigation_measure_id")), add_column(), add_external_fk_column("ros_ll.mitigation_measures", column_location("ros_ll.mitigation_measures_mitigation_devices→mitigation_measure_id")), flush_query())),
      mandatory_fk_column("SETTING_OPERATIONS_MITIGATION_MEASURES_OTHER_MITIGATION_MEASURES_USED_MEASURE_2_CODE", column_location("ros_ll.mitigation_measures_mitigation_devices→mitigation_device_code"), column_location("refs_fishery.mitigation_devices→code"), actions =  c(new_association_query("ros_ll.mitigation_measures", column_location("ros_ll.mitigation_measures_mitigation_devices→mitigation_measure_id")), add_column(), add_external_fk_column("ros_ll.mitigation_measures", column_location("ros_ll.mitigation_measures_mitigation_devices→mitigation_measure_id")), flush_query())),
      mandatory_fk_column("SETTING_OPERATIONS_MITIGATION_MEASURES_OTHER_MITIGATION_MEASURES_USED_MEASURE_3_CODE", column_location("ros_ll.mitigation_measures_mitigation_devices→mitigation_device_code"), column_location("refs_fishery.mitigation_devices→code"), actions =  c(new_association_query("ros_ll.mitigation_measures", column_location("ros_ll.mitigation_measures_mitigation_devices→mitigation_measure_id")), add_column(), add_external_fk_column("ros_ll.mitigation_measures", column_location("ros_ll.mitigation_measures_mitigation_devices→mitigation_measure_id")), flush_query())),
      mandatory_fk_column("SETTING_OPERATIONS_MITIGATION_MEASURES_OTHER_MITIGATION_MEASURES_USED_MEASURE_4_CODE", column_location("ros_ll.mitigation_measures_mitigation_devices→mitigation_device_code"), column_location("refs_fishery.mitigation_devices→code"), actions =  c(new_association_query("ros_ll.mitigation_measures", column_location("ros_ll.mitigation_measures_mitigation_devices→mitigation_measure_id")), add_column(), add_external_fk_column("ros_ll.mitigation_measures", column_location("ros_ll.mitigation_measures_mitigation_devices→mitigation_measure_id")), flush_query())))),
    sheet("E-SET-HAULING", "#[14] = E-SET-HAULING | From row 6 - 20 columns", 2, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      mandatory_simple_column("HAULING_OPERATIONS_START_HAULING_DATE_TIME_UTC", column_location("ros_ll.hauling_operations→start_hauling_date_and_time"), actions =  c(new_query(), add_column(), add_fk_column(column_location("ros_ll.fishing_events→hauling_operation_id")))),
      mandatory_simple_column("HAULING_OPERATIONS_START_HAULING_LATITUDE", column_location("ros_ll.hauling_operations→start_hauling_latitude"), actions =  c(add_column())),
      mandatory_simple_column("HAULING_OPERATIONS_START_HAULING_LONGITUDE", column_location("ros_ll.hauling_operations→start_hauling_longitude"), actions =  c(add_column())),
      mandatory_simple_column("HAULING_OPERATIONS_END_HAULING_DATE_TIME_UTC", column_location("ros_ll.hauling_operations→end_hauling_date_and_time"), actions =  c(add_column())),
      mandatory_simple_column("HAULING_OPERATIONS_END_HAULING_LATITUDE", column_location("ros_ll.hauling_operations→end_hauling_latitude"), actions =  c(add_column())),
      mandatory_simple_column("HAULING_OPERATIONS_END_HAULING_LONGITUDE", column_location("ros_ll.hauling_operations→end_hauling_longitude"), actions =  c(add_column())),
      optional_simple_column("HAULING_OPERATIONS_OFFAL_MANAGEMENT", column_location("ros_ll.hauling_operations→offal_management"), actions =  c(add_column())),
      optional_simple_column("HAULING_OPERATIONS_POSITIONS_OF_OFFAL_DISPOSAL_POSITION_1_CODE", column_location("ros_ll.hauling_offal_disposal_positions→offal_disposal_position"), actions =  c(new_association_query("ros_ll.hauling_operations", column_location("ros_ll.hauling_offal_disposal_positions→hauling_operation_id")), add_column(), add_external_fk_column("ros_ll.hauling_operations", column_location("ros_ll.hauling_offal_disposal_positions→hauling_operation_id")), flush_query())),
      optional_simple_column("HAULING_OPERATIONS_POSITIONS_OF_OFFAL_DISPOSAL_POSITION_2_CODE", column_location("ros_ll.hauling_offal_disposal_positions→offal_disposal_position"), actions =  c(new_association_query("ros_ll.hauling_operations", column_location("ros_ll.hauling_offal_disposal_positions→hauling_operation_id")), add_column(), add_external_fk_column("ros_ll.hauling_operations", column_location("ros_ll.hauling_offal_disposal_positions→hauling_operation_id")), flush_query())),
      optional_simple_column("HAULING_OPERATIONS_POSITIONS_OF_OFFAL_DISPOSAL_POSITION_3_CODE", column_location("ros_ll.hauling_offal_disposal_positions→offal_disposal_position"), actions =  c(new_association_query("ros_ll.hauling_operations", column_location("ros_ll.hauling_offal_disposal_positions→hauling_operation_id")), add_column(), add_external_fk_column("ros_ll.hauling_operations", column_location("ros_ll.hauling_offal_disposal_positions→hauling_operation_id")), flush_query())),
      optional_simple_column("HAULING_OPERATIONS_POSITIONS_OF_OFFAL_DISPOSAL_POSITION_4_CODE", column_location("ros_ll.hauling_offal_disposal_positions→offal_disposal_position"), actions =  c(new_association_query("ros_ll.hauling_operations", column_location("ros_ll.hauling_offal_disposal_positions→hauling_operation_id")), add_column(), add_external_fk_column("ros_ll.hauling_operations", column_location("ros_ll.hauling_offal_disposal_positions→hauling_operation_id")), flush_query())),
      ignored_column("HAULING_OPERATIONS_METHODS_TO_STUN_FISH_METHOD_1_CODE", "Removed in version 3.3.0"),
      ignored_column("HAULING_OPERATIONS_METHODS_TO_STUN_FISH_METHOD_2_CODE", "Removed in version 3.3.0"),
      ignored_column("HAULING_OPERATIONS_METHODS_TO_STUN_FISH_METHOD_3_CODE", "Removed in version 3.3.0"),
      ignored_column("HAULING_OPERATIONS_METHODS_TO_STUN_FISH_METHOD_4_CODE", "Removed in version 3.3.0"),
      mandatory_simple_column("HAULING_OPERATIONS_BIRD_SCARING_DEVICE_AT_HAULER", column_location("ros_ll.hauling_operations→bird_scaring_device_at_hauler"), actions =  c(add_column())),
      mandatory_simple_column("HAULING_OPERATIONS_NUM_HOOKS_RETRIEVED_DURING_OBSERVATION", column_location("ros_ll.hauling_operations→number_of_hooks_observed"), actions =  c(add_column())),
      mandatory_fk_column("HAULING_OPERATIONS_SAMPLING_PROTOCOL_CODE", column_location("ros_ll.hauling_operations→sampling_protocol_code"), column_location("refs_biological.sampling_protocols→code"), actions =  c(add_column(), flush_query())))),
    sheet("E-SET-HAULING-BITEOFFS", "#[15] = E-SET-HAULING-BITEOFFS | From row 6 - 4 columns", 2, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      optional_simple_column("HAULING_OPERATIONS_BITEOFFS_DETAILS_BRANCHLINE_CONFIGURATION_NUMBER", column_location("ros_ll.biteoffs_by_branchlines_set→branchline_configuration_original_id"), actions =  c(new_query(), add_column(), add_external_fk_column("ros_ll.hauling_operations", column_location("ros_ll.biteoffs_by_branchlines_set→hauling_operation_id")))),
      optional_simple_column("HAULING_OPERATIONS_BITEOFFS_DETAILS_BRANCHLINE_NUM_BITEOFFS", column_location("ros_ll.biteoffs_by_branchlines_set→number_of_biteoffs"), actions =  c(add_column(), flush_query())))),
    sheet("E-SET-CATCHES", "#[16] = E-SET-CATCHES | From row 6 - 12 columns", 3, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      mandatory_simple_column("CATCH_NUMBER", column_location("ros_ll.catch_details→catch_detail_original_id"), actions =  c(new_query(), add_column(), add_external_fk_column("ros_ll.fishing_events", column_location("ros_ll.catch_details→fishing_event_id")))),
      mandatory_fk_column("CATCH_DETAILS_SPECIES_CODE", column_location("ros_ll.catch_details→species_code"), column_location("refs_biological.species→code"), actions =  c(add_column())),
      mandatory_fk_column("CATCH_DETAILS_FATE_TYPE", column_location("ros_ll.catch_details→type_of_fate_code"), column_location("refs_biological.types_of_fate→code"), actions =  c(add_column())),
      mandatory_fk_column("CATCH_DETAILS_FATE_CODE", column_location("ros_ll.catch_details→fates_code"), column_location("refs_biological.fates→code"), actions =  c(add_column())),
      mandatory_fk_column("CATCH_DETAILS_SAMPLING_METHOD_CODE", column_location("ros_ll.catch_details→estimated_weight_sampling_method_code"), column_location("refs_biological.sampling_methods_for_catch_estimation→code"), actions =  c(add_column())),
      mandatory_simple_column("CATCH_DETAILS_NUM_FISH", column_location("ros_ll.catch_details→estimated_catch_in_numbers"), actions =  c(add_column())),
      optional_fk_column("CATCH_DETAILS_WEIGHT_PROCESSING_TYPE_CODE", column_location("ros_common.estimated_weights→processing_type_code"), column_location("refs_fishery.fish_processing_types→code"), actions =  c(add_column())),
      optional_measurement_column("CATCH_DETAILS_WEIGHT_VALUE", column_location("ros_ll.catch_details→estimated_weight_id"), "ros_common.estimated_weights", actions =  c(new_measurement_query(), add_column())),
      optional_measurement_unit_column("CATCH_DETAILS_WEIGHT_KG_T", c("KG", "T"), actions =  c(flush_measurement_query())),
      optional_fk_column("CATCH_DETAILS_WEIGHT_ESTIMATION_METHOD_CODE", column_location("ros_common.estimated_weights→weight_estimation_method_code"), column_location("refs_biological.sampling_methods_for_catch_estimation→code"), actions =  c(add_column(), flush_query())))),
    sheet("E-SET-CATCHES-SPECIMEN", "#[17] = E-SET-CATCHES-SPECIMEN | From row 6 - 32 columns", 4, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      ignored_column("CATCH_NUMBER", "Not used here"),
      mandatory_simple_column("SPECIMEN_NUMBER", column_location("ros_ll.specimens→specimen_original_id"), actions =  c(new_query(), add_fk_column(column_location("ros_common.specimens→catch_detail_id")), add_column())),
      mandatory_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_SAMPLING_PERIOD_CODE", column_location("ros_ll.specimens→b"), column_location("refs_biological.sampling_periods→code"), actions =  c(add_column())),
      mandatory_fk_column("SPECIMEN_DETAILS_NON_TARGET_SPECIES_ADDITIONAL_DETAILS_CONDITION_AT_CAPTURE_CODE", column_location("ros_common.additional_details_on_non_target_species→condition_at_capture_code"), column_location("refs_biological.incidental_captures_conditions→code"), actions =  c(new_query(), add_fk_column(column_location("ros_common.specimens→additional_specimen_details_non_target_species_id")), add_column())),
      mandatory_fk_column("SPECIMEN_DETAILS_NON_TARGET_SPECIES_ADDITIONAL_DETAILS_CONDITION_AT_RELEASE_CODE", column_location("ros_common.additional_details_on_non_target_species→condition_at_release_code"), column_location("refs_biological.incidental_captures_conditions→code"), actions =  c(add_column(), flush_query())),
      optional_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_DEPREDATION_DETAILS_DEPREDATION_SOURCE_CODE", column_location("ros_common.depredation_details→depredation_source_code"), column_location("refs_biological.scars→code"), "Fixme : why not using refs_biological.depredation_sources", actions =  c(new_query(), add_fk_column(column_location("ros_common.specimens→depredation_detail_id")), add_column())),
      optional_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_DEPREDATION_DETAILS_OBSERVED_PREDATOR_CODE", column_location("ros_common.depredation_details→predator_observed_code"), column_location("refs_biological.species→code"), actions =  c(add_column(), flush_query())),
      mandatory_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_SAMPLING_METHOD_CODE", column_location("ros_common.biometric_information→bio_collection_sampling_method_code"), column_location("refs_biological.sampling_methods_for_sampling_collections→code"), actions =  c(add_column())),
      mandatory_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_1_TYPE_CODE", column_location("ros_common.measured_lengths→code"), column_location("refs_biological.measurements→code"), actions =  c(new_measurement_query(), add_fk_column(column_location("ros_common.biometric_information→measured_length_id")), add_column())),
      mandatory_measurement_column("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_1_VALUE_CM", column_location("ros_common.biometric_information→measured_length_id"), "ros_common.measured_lengths", "CM", actions =  c(add_column())),
      mandatory_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_1_MEASURING_TOOL_CODE", column_location("ros_common.measured_lengths→length_measuring_tool_code"), column_location("refs_biological.measurement_tools→code"), actions =  c(add_column())),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_1_IS_STRAIGHT", column_location("ros_common.measured_lengths→straight"), actions =  c(add_column(), flush_measurement_query())),
      optional_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_2_TYPE_CODE", column_location("ros_common.measured_lengths→code"), column_location("refs_biological.measurements→code"), actions =  c(new_measurement_query(), add_fk_column(column_location("ros_common.biometric_information→alternative_measured_length_id")), add_column())),
      optional_measurement_column("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_2_VALUE_CM", column_location("ros_common.biometric_information→alternative_measured_length_id"), "ros_common.measured_lengths", "CM", actions =  c(add_column())),
      optional_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_2_MEASURING_TOOL_CODE", column_location("ros_common.measured_lengths→length_measuring_tool_code"), column_location("refs_biological.measurement_tools→code"), actions =  c(add_column())),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_LENGTH_2_IS_STRAIGHT", column_location("ros_common.measured_lengths→straight"), actions =  c(add_column(), flush_measurement_query())),
      optional_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_WEIGHT_PROCESSING_TYPE_CODE", column_location("ros_common.estimated_weights→processing_type_code"), column_location("refs_fishery.fish_processing_types→code"), actions =  c(new_measurement_query(), add_fk_column(column_location("ros_common.biometric_information→estimated_weight_id")), add_column())),
      optional_measurement_column("SPECIMEN_DETAILS_ALL_SPECIES_WEIGHT_VALUE_KG", column_location("ros_common.biometric_information→estimated_weight_id"), "ros_common.estimated_weights", "KG", actions =  c(add_column())),
      optional_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_WEIGHT_ESTIMATION_METHOD_CODE", column_location("ros_common.estimated_weights→weight_estimation_method_code"), column_location("refs_biological.measurement_tools→code"), actions =  c(add_column(), flush_measurement_query())),
      optional_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_SEX", column_location("ros_common.biometric_information→sex_code"), column_location("refs_biological.sex→code"), actions =  c(add_column())),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_MATURITY_SCALE", column_location("ros_common.maturity_stages→scale"), actions =  c(new_measurement_query(), add_fk_column(column_location("ros_common.biometric_information→maturity_stage_id")), add_column())),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_MATURITY_STAGE", column_location("ros_common.maturity_stages→maturity_level"), actions =  c(add_column(), flush_measurement_query())),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_SAMPLE_COLLECTED_TYPE", column_location("ros_common.sample_collection_details→sample_type"), actions =  c(add_column())),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_SAMPLE_COLLECTED_PRESERVATION_METHOD", column_location("ros_common.sample_collection_details→preservation_method"), actions =  c(add_column(), flush_query())),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_RELEASE", column_location("ros_ll.tag_details→tag_release"), actions =  c(new_query(), add_fk_column(column_location("ros_common.specimens→tag_detail_id")), add_column())),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_RECOVERY", column_location("ros_ll.tag_details→tag_recovery"), actions =  c(add_column())),
      optional_fk_column("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_TYPE_CODE", column_location("ros_ll.tag_details→tag_type_code"), column_location("refs_biological.tag_types→code"), actions =  c(add_column())),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_TAG_NUMBER_1", column_location("ros_ll.tag_details→tag_original_id"), actions =  c(add_column())),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_TAG_NUMBER_2", column_location("ros_ll.tag_details→alternate_tag_original_id"), actions =  c(add_column())),
      optional_simple_column("SPECIMEN_DETAILS_ALL_SPECIES_TAG_DETAILS_FINDER_NAME_AND_CONTACT_DETAILS", column_location("ros_common.person_contact_details→full_name"), actions =  c(new_query(), add_fk_column(column_location("ros_ll.tag_details→tag_finder_id")), flush_query())))),
    sheet("E-SET-CATCHES-SPECIMEN-SSI", "#[18] = E-SET-CATCHES-SPECIMEN-SSI | From row 6 - 16 columns", 4, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Not used here"),
      ignored_column("SET_NUMBER", "Not used here"),
      ignored_column("CATCH_NUMBER", "Not used here"),
      ignored_column("SPECIMEN_NUMBER", "Not used here"),
      mandatory_fk_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_GEAR_INTERACTION_CODE", column_location("ros_ll.additional_catch_details_on_ssi→gear_interaction_code"), column_location("refs_biological.gear_interactions→code"), actions =  c(new_query(), add_fk_column(column_location("ros_common.specimens→additional_catch_details_on_ssis_id")), add_column())),
      optional_fk_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_HOOK_TYPE_CODE", column_location("ros_ll.additional_catch_details_on_ssi→hook_type_code"), column_location("refs_fishery.hook_types→code"), "Added in version 3.3.0", actions =  c(add_column())),
      optional_fk_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_BAIT_CONDITION_CODE", column_location("ros_ll.additional_catch_details_on_ssi→bait_condition_code"), column_location("refs_biological.bait_conditions→code"), actions =  c(add_column())),
      optional_fk_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_BAIT_TYPE_CODE", column_location("os_ll.additional_catch_details_on_ssi→bait_type"), column_location("refs_biological.bait_types→code"), actions =  c(add_column())),
      mandatory_fk_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_LEADER_MATERIAL_CODE", column_location("ros_ll.additional_catch_details_on_ssi→leader_material_type_code"), column_location("refs_fishery.line_material_types→code"), actions =  c(add_column())),
      optional_measurement_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_LEADER_DIAMETER_MM", column_location("ros_ll.additional_catch_details_on_ssi→leader_thickness_id"), "ros_common.thicknesses", "MM", actions =  c(new_measurement_query(), add_column(), flush_measurement_query())),
      optional_fk_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_DE_HOOKER_DEVICE_CODE", column_location("ros_ll.additional_catch_details_on_ssi→dehooker_device_code"), column_location("refs_fishery.dehooker_types→code"), actions =  c(add_column())),
      optional_simple_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_LIGHT_ATTACHED", column_location("ros_ll.additional_catch_details_on_ssi→light_attached_to_branchline"), actions =  c(add_column())),
      optional_simple_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_BROUGHT_ONBOARD", column_location("ros_ll.additional_catch_details_on_ssi→brought_on_board"), actions =  c(add_column())),
      optional_fk_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_HANDLING_METHOD_CODE", column_location("ros_ll.additional_catch_details_on_ssi→handling_method_code"), column_location("refs_biological.handling_methods→code"), actions =  c(add_column())),
      optional_simple_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_REVIVAL", column_location("ros_ll.additional_catch_details_on_ssi→revival"), actions =  c(add_column())),
      optional_simple_column("SPECIMEN_DETAILS_ADDITIONAL_CATCH_DETAILS_SSI_PHOTO_ID", column_location("ros_ll.additional_catch_details_on_ssi→photo_id"), actions =  c(add_column(), flush_query())))),
    sheet("T-EVENTS", "#[19] = T-EVENTS | From row 6 - 15 columns", 1, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Removed in version 3.3.0"),
      ignored_column("TRANSSHIPMENT_NUMBER", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_START_EVENT_DATE_TIME_UTC", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_START_EVENT_LATITUDE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_START_EVENT_LONGITUDE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_END_EVENT_DATE_TIME_UTC", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_END_EVENT_LATITUDE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_END_EVENT_LONGITUDE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_CATEGORY_CODE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_NAME", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_FLAG_OR_CHARTERING_CODE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_IRCS", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_REGISTRATION_COUNTRY_CODE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_REGISTRATION_PORT_CODE", "Removed in version 3.3.0"),
      ignored_column("VESSEL_TRANSSHIPMENT_EVENT_CARRIER_OR_FISHING_VESSEL_REGISTRATION_NUMBER", "Removed in version 3.3.0"))),
    sheet("T-PRODUCTS", "#[20] = T-PRODUCTS | From row 6 - 6 columns", 1, c(
      ignored_column("OBSERVED_TRIP_NUMBER", "Removed in version 3.3.0"),
      ignored_column("TRANSSHIPMENT_NUMBER", "Removed in version 3.3.0"),
      ignored_column("PRODUCT_TRANSSHIPPED_SPECIES_CODE", "Removed in version 3.3.0"),
      ignored_column("PRODUCT_TRANSSHIPPED_PROCESSING_TYPE_CODE", "Removed in version 3.3.0"),
      ignored_column("PRODUCT_TRANSSHIPPED_QUANTITY_VALUE", "Removed in version 3.3.0"),
      ignored_column("PRODUCT_TRANSSHIPPED_QUANTITY_KG_T", "Removed in version 3.3.0")))))

#' Load xls content using ROS_LL_v3_2_1_MODEL
#'
#' @param file The xls file to import
#' @return the loaded xls as a list of data.table (one per none empty sheet)
#' @export
load_xls_ROS_LL_v3_2_1 <- function(file) {
  load_xls(file, ROS_LL_v3_2_1_MODEL)
}

#' Create import context using ROS_LL_v3_2_1_MODEL
#'
#' @param file path to xsl file to load
#' @param connection jdbc connectoion to db
#' @return the import context (See ImportContext class)
#' @export
import_context_ROS_LL_v3_2_1 <- function(file, connection, extra_data_tables) {
  import_context(ROS_LL_v3_2_1_MODEL, file, connection, extra_data_tables)
}
